# ========== builder ==========

FROM rust:1.88-slim AS builder

WORKDIR /src
ENV CARGO_INCREMENTAL=0

RUN apt-get update && apt-get install -y clang libc++-dev git && rm -rf /var/lib/apt/lists/*

COPY . .
RUN git rev-parse HEAD

# Enable the e2e_tests feature by default for the gateway build
ARG CARGO_BUILD_FLAGS="--features e2e_tests"

RUN cargo build -p gateway $CARGO_BUILD_FLAGS && \
    mkdir -p /release && \
    cp /src/target/debug/gateway /release/gateway

# ========== base ==========

FROM debian:trixie-slim AS base

RUN apt-get update && apt-get install -y ca-certificates openssl wget && rm -rf /var/lib/apt/lists/*

# ========== gateway ==========

FROM base AS gateway

RUN useradd -m -s /bin/bash gateway

USER gateway

COPY --from=builder /release/gateway /usr/local/bin/gateway

WORKDIR /app

EXPOSE 3000

ENTRYPOINT ["gateway"]
