// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdaptiveExperimentationAlgorithm } from "./AdaptiveExperimentationAlgorithm";

/**
 * Loaded adaptive experimentation config.
 * Wraps a loaded `TrackAndStopConfig` with `algorithm` metadata.
 */
export type AdaptiveExperimentationConfig = {
  algorithm: AdaptiveExperimentationAlgorithm;
  metric: string;
  candidate_variants: Array<string>;
  fallback_variants: Array<string>;
  min_samples_per_variant: bigint;
  delta: number;
  epsilon: number;
  min_prob: number | null;
  max_samples_per_variant?: bigint;
  namespace?: string;
};
