// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Algorithm used for adaptive experimentation.
 * Currently only `TrackAndStop` is supported.
 */
export type AdaptiveExperimentationAlgorithm = "track_and_stop";
