// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoevalContentBlock } from "./AutoevalContentBlock";
import type { EventPayloadUserQuestion } from "./EventPayloadUserQuestion";

/**
 * A single example to label, with context and questions.
 */
export type AutoevalLabelingExample = {
  /**
   * Rich content blocks providing context (e.g. the prompt and response).
   */
  context: Array<AutoevalContentBlock>;
  /**
   * Questions about this example (e.g. a label choice and optional explanation).
   */
  questions: Array<EventPayloadUserQuestion>;
};
