// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rendered markdown content in an autoeval example.
 */
export type AutoEvalMarkdownContentBlock = { text: string; label?: string };
