// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Tool result that can carry either a structured JSON value or a legacy serialized string.
 *
 * New producers should use `AutopilotToolResult::typed`. Consumers should use
 * `AutopilotToolResult::value()` which returns the structured value directly
 * or parses the legacy string as a fallback.
 */
export type AutopilotToolResult = { result_value: JsonValue, } | { result: string, };
