// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A block of rich content displayed alongside an autoeval example.
 */
export type AutoevalContentBlock =
  | { type: "markdown"; text: string }
  | { type: "json"; data: JsonValue; label?: string }
  | { type: "collapsible"; label: string; text: string };
