// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MultipleChoiceOption } from "./MultipleChoiceOption";

/**
 * A multiple-choice labeling question within an autoeval example.
 */
export type AutoEvalLabelQuestion = { id: string, header: string, question: string, options: Array<MultipleChoiceOption>, };
