// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutoEvalExampleSourceInference = {
  /**
   * The inference ID of the historical datapoint for auto evals
   */
  id: string;
};
