// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoevalContentBlock } from "./AutoevalContentBlock";
import type { AutoevalExplanationQuestion } from "./AutoevalExplanationQuestion";
import type { AutoevalLabelQuestion } from "./AutoevalLabelQuestion";

/**
 * A single example to label, with context and a structured labeling question.
 */
export type AutoevalLabelingExample = {
  /**
   * Rich content blocks providing context (e.g. the prompt and response).
   */
  context: Array<AutoevalContentBlock>;
  /**
   * The multiple-choice labeling question for this example.
   */
  label_question: AutoevalLabelQuestion;
  /**
   * An optional free-response explanation question.
   */
  explanation_question?: AutoevalExplanationQuestion;
};
