// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoEvalJsonContentBlock } from "./AutoEvalJsonContentBlock";
import type { AutoEvalMarkdownContentBlock } from "./AutoEvalMarkdownContentBlock";

/**
 * A block of rich content displayed alongside an autoeval example.
 */
export type AutoEvalContentBlock =
  | ({ type: "markdown" } & AutoEvalMarkdownContentBlock)
  | ({ type: "json" } & AutoEvalJsonContentBlock);
