// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A free-response explanation question within an autoeval example.
 */
export type AutoevalExplanationQuestion = {
  id: string;
  header: string;
  question: string;
};
