// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BaseModelTable<T> = {
  /**
   * The underlying HashMap of explicitly configured models.
   *
   * **WARNING:** This does NOT contain shorthand models (e.g. `openai::gpt-5`).
   * Shorthand models are constructed dynamically at lookup time.
   * Use `BaseModelTable::get()` instead, which handles both explicit and shorthand models.
   */
  table: { [key in string]: T };
  global_outbound_http_timeout: [number, number];
};
