// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which Bedrock API to use for inference.
 */
export type BedrockApiType = "aws_converse" | "anthropic" | "auto";
