// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pricing configuration for prompt caching cost estimation.
 *
 * These values should be derived from the model provider's `cost` config
 * in `tensorzero.toml`. The caller extracts the base input price from the
 * existing cost pointers and provides cache-specific multipliers.
 */
export type CachingPricingConfig = {
  /**
   * Base input token price in dollars per million tokens.
   * Derived from the provider's `cost` config (e.g. `cost_per_million` for
   * the input token pointer).
   */
  input_price_per_million: number;
  /**
   * Multiplier for cached token reads (e.g. 0.1 for Anthropic = 90% savings).
   * Default: 0.1
   */
  cache_read_multiplier: number;
  /**
   * Multiplier for cache writes with 5-minute TTL (e.g. 1.25 for Anthropic).
   * Default: 1.25
   */
  cache_write_5min_multiplier: number;
  /**
   * Multiplier for cache writes with 1-hour TTL (e.g. 2.0 for Anthropic).
   * Default: 2.0
   */
  cache_write_1hr_multiplier: number;
};
