// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CostEstimate = {
  /**
   * Total estimated cost of all samples without caching (dollars).
   */
  total_cost_no_caching: number;
  /**
   * Total estimated cost with caching enabled (dollars).
   */
  total_cost_with_caching: number;
  /**
   * Projected savings percentage.
   */
  savings_pct: number;
};
