// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response containing the count of distinct episodes by task_name.
 */
export type CountWorkflowEvaluationRunEpisodesByTaskNameResponse = {
  count: number;
};
