// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolOutcome } from "./ToolOutcome";

/**
 * Minimal tool result payload for creating events.
 * Omits server-enriched fields like `tool_call_name`, `tool_call_arguments`, etc.
 */
export type CreateEventPayloadToolResult = { tool_call_event_id: string, outcome: ToolOutcome, };
