// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateDatapointRequest } from "./CreateDatapointRequest";

/**
 * Combined request for creating datapoints that includes the dataset name.
 * In the HTTP API, `dataset_name` comes from the URL path, but tools and
 * embedded clients need it in a single request struct.
 */
export type CreateDatapointsToolParams = {
  /**
   * The name of the dataset to create datapoints in.
   */
  dataset_name: string;
  /**
   * The datapoints to create.
   */
  datapoints: Array<CreateDatapointRequest>;
};
