// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventPayload } from "./EventPayload";

/**
 * HTTP request body for creating an event.
 *
 * This is the request type used by the HTTP handler. The `deployment_id` is
 * injected from the gateway's app state, so it's not included in this request.
 */
export type CreateEventGatewayRequest = {
  payload: EventPayload;
  /**
   * Used for idempotency when adding events to an existing session.
   */
  previous_user_message_event_id?: string;
};
