// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Credential location that also allows hardcoded string values.
 * Used for non-sensitive fields like AWS region and endpoint_url.
 */
export type CredentialLocationOrHardcoded =
  | { Hardcoded: string }
  | { Location: string };
