// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filter by whether an inference has a demonstration.
 */
export type DemonstrationFeedbackFilter = { has_demonstration: boolean };
