// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Statistics for a single evaluation run and metric.
 */
export type EvaluationStatistics = {
  evaluation_run_id: string;
  metric_name: string;
  datapoint_count: number;
  mean_metric: number;
  ci_lower?: number;
  ci_upper?: number;
};
