// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvaluationConfig } from "./EvaluationConfig";
import type { EvaluationFunctionConfig } from "./EvaluationFunctionConfig";

/**
 * Identifies the evaluation to run.
 */
export type EvaluationIdentifier = { evaluation_config: EvaluationConfig, evaluation_name: string, function_config: EvaluationFunctionConfig, } | { function_name: string, evaluator_names: Array<string>, };
