// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Usage statistics for a single evaluation run.
 */
export type EvaluationUsageStatistics = {
  evaluation_run_id: string;
  inference_count: number;
  avg_input_tokens?: number;
  avg_output_tokens?: number;
  avg_cost?: number;
  avg_processing_time_ms?: number;
};
