// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCallAuthorizationStatus } from "./ToolCallAuthorizationStatus";
import type { ToolCallDecisionSource } from "./ToolCallDecisionSource";
import type { ToolOutcome } from "./ToolOutcome";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Tool result payload for an event.
 *
 * Includes enriched fields from the originating tool call and authorization events,
 * making this payload self-contained for UI rendering.
 */
export type EventPayloadToolResult = { tool_call_event_id: string, outcome: ToolOutcome, 
/**
 * Populated by the server from the originating tool call event.
 */
tool_call_name: string, 
/**
 * Populated by the server from the originating tool call event.
 */
tool_call_arguments: JsonValue, 
/**
 * Authorization source (Ui/Automatic/Whitelist).
 */
tool_call_authorization_source: ToolCallDecisionSource, 
/**
 * Authorization status (Approved/Rejected/NotAvailable).
 */
tool_call_authorization_status: ToolCallAuthorizationStatus, };
