// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExperimentationConfigWithNamespaces } from "./ExperimentationConfigWithNamespaces";
import type { SchemaData } from "./SchemaData";
import type { ToolChoice } from "./ToolChoice";
import type { VariantInfo } from "./VariantInfo";

export type FunctionConfigChat = {
  variants: { [key in string]: VariantInfo };
  schemas: SchemaData;
  tools: Array<string>;
  tool_choice: ToolChoice;
  parallel_tool_calls: boolean | null;
  description: string | null;
  experimentation: ExperimentationConfigWithNamespaces;
};
