// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventPayloadAutoEvalExampleLabeling } from "./EventPayloadAutoEvalExampleLabeling";
import type { EventPayloadError } from "./EventPayloadError";
import type { EventPayloadMessage } from "./EventPayloadMessage";
import type { EventPayloadStatusUpdate } from "./EventPayloadStatusUpdate";
import type { EventPayloadToolResult } from "./EventPayloadToolResult";
import type { EventPayloadUserQuestions } from "./EventPayloadUserQuestions";
import type { EventPayloadUserQuestionsAnswers } from "./EventPayloadUserQuestionsAnswers";
import type { EventPayloadVisualization } from "./EventPayloadVisualization";
import type { GatewayEventPayloadToolCall } from "./GatewayEventPayloadToolCall";
import type { GatewayEventPayloadToolCallAuthorization } from "./GatewayEventPayloadToolCallAuthorization";

/**
 * Event payload as seen by gateway consumers.
 *
 * Uses `GatewayEventPayloadToolCallAuthorization` which excludes `NotAvailable` status.
 */
export type GatewayEventPayload = { "type": "message" } & EventPayloadMessage | { "type": "error" } & EventPayloadError | { "type": "status_update" } & EventPayloadStatusUpdate | { "type": "tool_call" } & GatewayEventPayloadToolCall | { "type": "tool_call_authorization" } & GatewayEventPayloadToolCallAuthorization | { "type": "tool_result" } & EventPayloadToolResult | { "type": "visualization" } & EventPayloadVisualization | { "type": "user_questions" } & EventPayloadUserQuestions | { "type": "user_questions_answers" } & EventPayloadUserQuestionsAnswers | { "type": "auto_eval_example_labeling" } & EventPayloadAutoEvalExampleLabeling | { "type": "unknown" };
