// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutopilotStatus } from "./AutopilotStatus";
import type { GatewayEvent } from "./GatewayEvent";

/**
 * Stream update as seen by gateway consumers.
 *
 * Uses `GatewayEvent` which excludes `NotAvailable` authorization status.
 */
export type GatewayStreamUpdate = {
  event: GatewayEvent;
  status: AutopilotStatus;
};
