// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Authorization status for tool calls as seen by gateway consumers.
 *
 * This is a narrower type than `ToolCallAuthorizationStatus` that excludes
 * `NotAvailable` since that status is filtered out before reaching consumers.
 */
export type GatewayToolCallAuthorizationStatus =
  | { type: "approved" }
  | { type: "rejected"; reason: string };
