// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigLoadingError } from "./ConfigLoadingError";

/**
 * Response containing a TOML-editable config from stored config.
 */
export type GetConfigTomlResponse = {
  /**
   * Human-readable TOML config with path strings instead of inlined file contents.
   */
  toml: string;
  /**
   * File-backed content referenced by the TOML, keyed by the path string in the TOML body.
   */
  path_contents: { [key in string]: string };
  /**
   * The hash identifying this config version.
   */
  hash: string;
  /**
   * Compare-and-swap signature for the full editable document.
   */
  base_signature: string;
  /**
   * User-defined tags for categorizing or labeling this config.
   */
  tags: { [key in string]: string };
  /**
   * Non-fatal errors encountered while loading the config from the database.
   * Present when some config items failed to load but the gateway started anyway.
   */
  loading_errors: Array<ConfigLoadingError>;
};
