// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Combined request for getting datapoints that includes the optional dataset name.
 * In the HTTP API, `dataset_name` comes from the URL path, but tools and
 * embedded clients need it in a single request struct.
 */
export type GetDatapointsToolParams = {
  /**
   * The name of the dataset (optional, but recommended for performance).
   */
  dataset_name: string | null;
  /**
   * The IDs of the datapoints to retrieve.
   */
  ids: Array<string>;
};
