// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvaluationResultRow } from "./EvaluationResultRow";

/**
 * Response containing paginated evaluation results.
 */
export type GetEvaluationResultsResponse = {
  results: Array<EvaluationResultRow>;
};
