// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvaluationUsageStatistics } from "./EvaluationUsageStatistics";

/**
 * Response containing evaluation usage statistics.
 */
export type GetEvaluationUsageStatisticsResponse = {
  usage_statistics: Array<EvaluationUsageStatistics>;
};
