// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for the get_feedback_by_target_id tool (visible to LLM).
 */
export type GetFeedbackByTargetIdToolParams = { 
/**
 * The target ID (inference or episode) to get feedback for.
 */
target_id: string, 
/**
 * Maximum number of feedback entries to return.
 */
limit: number | null, };
