// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VariantUsageTimePoint } from "./VariantUsageTimePoint";

/**
 * Response containing variant usage timeseries data.
 */
export type GetVariantUsageResponse = {
  /**
   * The variant usage data points.
   */
  data: Array<VariantUsageTimePoint>;
};
