// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VariantUsageTimePoint } from "./VariantUsageTimePoint";

/**
 * Response containing variant usage timeseries data.
 */
export type GetVariantUsageResponse = {
  /**
   * The quantile inputs (e.g. [0.001, 0.005, ..., 0.999]) — populated when ClickHouse
   * is the backend, None on Postgres.
   */
  quantiles?: Array<number>;
  /**
   * The variant usage data points.
   */
  data: Array<VariantUsageTimePoint>;
};
