// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowEvaluationRun } from "./WorkflowEvaluationRun";

/**
 * Response containing a list of workflow evaluation runs by IDs.
 */
export type GetWorkflowEvaluationRunsResponse = {
  runs: Array<WorkflowEvaluationRun>;
};
