// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response containing inference count with feedback count
 */
export type InferenceWithFeedbackCountResponse = {
  /**
   * Number of feedbacks for the metric
   */
  feedback_count: bigint;
  /**
   * Number of inferences matching the metric threshold criteria
   */
  inference_count: bigint;
};
