// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * JSON mode for inference requests.
 */
export type JsonMode = "off" | "on" | "strict" | "tool";
