// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptimizationJobInfo } from "./OptimizationJobInfo";

/**
 * Response from the optimization workflow tool.
 */
export type LaunchOptimizationWorkflowToolOutput = {
  /**
   * The final job info (Completed or Failed).
   */
  result: OptimizationJobInfo;
};
