// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Legacy `type = "static_weights"` config. Converts to `StaticExperimentationConfig` directly.
 */
export type LegacyStaticWeightsExperimentationConfig = {
  candidate_variants: { [key in string]: number };
  fallback_variants: Array<string>;
};
