// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FloatComparisonOperator } from "./FloatComparisonOperator";
import type { MetricConfigLevel } from "./MetricConfigLevel";
import type { MetricConfigType } from "./MetricConfigType";

export type MetricFilter = {
  metric: string;
  metric_type: MetricConfigType;
  operator: FloatComparisonOperator;
  threshold: number;
  join_on: MetricConfigLevel;
};
