// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InferenceCacheBackend } from "./InferenceCacheBackend";
import type { ValkeyModelInferenceCacheConfig } from "./ValkeyModelInferenceCacheConfig";

export type ModelInferenceCacheConfig = {
  /**
   * Whether caching is enabled.
   * - `true`: require a cache backend (fail startup if unavailable)
   * - `null` (default): use cache if available, warn and continue if not
   * - `false`: disable caching entirely
   */
  enabled?: boolean;
  /**
   * Which cache backend to use.
   */
  backend: InferenceCacheBackend;
  valkey: ValkeyModelInferenceCacheConfig;
};
