// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedRequestMessage } from "./ResolvedRequestMessage";

/**
 * For use in rendering for optimization purposes
 */
export type ModelInput = {
  system: string | null;
  messages: Array<ResolvedRequestMessage>;
};
