// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Detail } from "./Detail";
import type { StoragePath } from "./StoragePath";

/**
 * A file stored in an object storage backend, without data.
 * This struct can be stored in the database. It's used by `StoredFile` (`StoredInput`).
 * Note: `File` supports both `ObjectStorageFilePointer` and `ObjectStorageFile`.
 */
export type ObjectStoragePointer = {
  source_url?: string;
  mime_type: string;
  storage_path: StoragePath;
  detail?: Detail;
  filename?: string;
};
