// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects the primary datastore used for observability writes (inferences, feedback).
 *
 * - `Auto` (default): prefers ClickHouse if available, falls back to Postgres.
 * - `ClickHouse`: explicitly use ClickHouse.
 * - `Postgres`: explicitly use Postgres.
 */
export type ObservabilityBackend = "auto" | "clickhouse" | "postgres";
