// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiclOptimizationJobHandle } from "./DiclOptimizationJobHandle";
import type { FireworksSFTJobHandle } from "./FireworksSFTJobHandle";
import type { GCPVertexGeminiSFTJobHandle } from "./GCPVertexGeminiSFTJobHandle";
import type { GEPAJobHandle } from "./GEPAJobHandle";
import type { OpenAIRFTJobHandle } from "./OpenAIRFTJobHandle";
import type { OpenAISFTJobHandle } from "./OpenAISFTJobHandle";
import type { TogetherSFTJobHandle } from "./TogetherSFTJobHandle";

export type OptimizationJobHandle =
  | ({ type: "dicl" } & DiclOptimizationJobHandle)
  | ({ type: "openai_sft" } & OpenAISFTJobHandle)
  | ({ type: "openai_rft" } & OpenAIRFTJobHandle)
  | ({ type: "fireworks_sft" } & FireworksSFTJobHandle)
  | ({ type: "gcp_vertex_gemini_sft" } & GCPVertexGeminiSFTJobHandle)
  | ({ type: "gepa" } & GEPAJobHandle)
  | ({ type: "together_sft" } & TogetherSFTJobHandle);
