// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderDirection } from "./OrderDirection";

/**
 * Order by clauses for querying inferences.
 */
export type OrderBy = {
  /**
   * The ordering direction.
   */
  direction: OrderDirection;
} & (
  | { by: "timestamp" }
  | {
      by: "metric";
      /**
       * The name of the metric to order by.
       */
      name: string;
    }
  | { by: "search_relevance" }
);
