// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderToolScope } from "./ProviderToolScope";
import type { JsonValue } from "./serde_json/JsonValue";

export type ProviderTool = { scope: ProviderToolScope; tool: JsonValue };
