// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderToolScopeModelProvider } from "./ProviderToolScopeModelProvider";

export type ProviderToolScope = null | ProviderToolScopeModelProvider;
