// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiType } from "./ApiType";

/**
 * A single entry in the raw response array, representing raw response data from one model inference.
 * This preserves the original provider-specific response string that TensorZero normalizes.
 */
export type RawResponseEntry = {
  model_inference_id?: string;
  provider_type: string;
  api_type: ApiType;
  data: string;
};
