// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Evaluator that checks whether an inference's text output matches regex patterns.
 *
 * At least one of `must_match` or `must_not_match` must be specified.
 * If both are specified, the result is the logical AND: `must_match` matches AND `must_not_match` does not match.
 */
export type RegexConfig = {
  /**
   * Regex pattern that the inference output must match for the evaluation to pass.
   */
  must_match?: string;
  /**
   * Regex pattern that the inference output must *not* match for the evaluation to pass.
   */
  must_not_match?: string;
};
