// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheEnabledMode } from "./CacheEnabledMode";

/**
 * Parameters for running an evaluation.
 */
export type RunEvaluationParams = {
  /**
   * Name of the evaluation to run (must be defined in config).
   */
  evaluation_name: string;
  /**
   * Name of the dataset to run on.
   * Either `dataset_name` or `datapoint_ids` must be provided, but not both.
   */
  dataset_name: string | null;
  /**
   * Specific datapoint IDs to evaluate.
   * Either `dataset_name` or `datapoint_ids` must be provided, but not both.
   */
  datapoint_ids: Array<string> | null;
  /**
   * Name of the variant to evaluate.
   */
  variant_name: string;
  /**
   * Number of concurrent inference requests (default: 10).
   */
  concurrency: number;
  /**
   * Cache configuration for inference requests (default: On).
   */
  inference_cache: CacheEnabledMode;
  /**
   * Maximum number of datapoints to evaluate.
   */
  max_datapoints: number | null;
  /**
   * Precision targets for adaptive stopping (evaluator name -> target CI half-width).
   */
  precision_targets: { [key in string]: number };
  /**
   * Whether to include per-datapoint results in the response.
   */
  include_datapoint_results: boolean;
  /**
   * Additional tags to apply to all inferences made during the evaluation.
   * These tags will be added to each inference, with internal evaluation tags
   * taking precedence in case of conflicts.
   */
  tags: { [key in string]: string };
};
