// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricConfigOptimize } from "./MetricConfigOptimize";

/**
 * Metric metadata from an evaluation run.
 */
export type RunMetricMetadata = { name: string, evaluator_name?: string, 
/**
 * `boolean` or `float`
 */
value_type: string, optimize?: MetricConfigOptimize, };
