// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JSONSchema } from "./JSONSchema";

/**
 * Wraps a schema with metadata indicating whether it was defined using legacy syntax
 * (e.g., `user_schema`, `assistant_schema`, `system_schema`) or new syntax (e.g., `schemas.<name>`).
 * This is used to determine whether to show a "Legacy" badge in the UI.
 */
export type SchemaWithMetadata = {
  schema: JSONSchema;
  legacy_definition: boolean;
};
