// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SegmentStability = {
  /**
   * Fraction of consecutive pairs with identical tools.
   */
  tools: number;
  /**
   * Fraction of consecutive pairs with identical system prompt.
   */
  system: number;
  /**
   * Per-position stability for messages (position → fraction identical).
   */
  messages_by_position: Array<number>;
  /**
   * Number of unique tool definitions across all samples.
   */
  tools_unique_count: number;
  /**
   * Number of unique system prompts across all samples.
   */
  system_unique_count: number;
};
