// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A status update within a session.
 */
export type StatusUpdate = { type: "text"; text: string };
