// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WeightedVariants } from "./WeightedVariants";

/**
 * Unified static experimentation config that replaces both `uniform` and `static_weights`.
 *
 * `candidate_variants` is mandatory and stored as a `BTreeMap<String, f64>`.
 * It can be deserialized from either a list of variant names (equal weights of 1.0 each)
 * or a map of variant names to explicit weights.
 *
 * `fallback_variants` is optional and defaults to an empty list.
 */
export type StaticExperimentationConfig = {
  candidate_variants: WeightedVariants;
  fallback_variants?: Array<string>;
};
