// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageKind } from "./StorageKind";

/**
 * Path to a file in an object storage backend.
 * This is part of the public API for `File`s. In particular, this is useful for roundtripping
 * unresolved inputs from stored inferences or datapoints, without requiring clients to fetch
 * file data first.
 */
export type StoragePath = { kind: StorageKind; path: string };
