// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TogetherDefaults } from "./TogetherDefaults";
import type { TogetherSFTProviderConfig } from "./TogetherSFTProviderConfig";

export type TogetherProviderTypeConfig = {
  sft?: TogetherSFTProviderConfig;
  defaults: TogetherDefaults;
};
