// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonControlToolError } from "./NonControlToolError";

/**
 * The type written in `ToolOutcome::Failure` for tool errors.
 */
export type ToolFailure = { "kind": "control", message: string, } | { "kind": "tool", error: NonControlToolError, } | { "kind": "database", message: string, };
