// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllowedTools } from "./AllowedTools";
import type { FunctionToolConfig } from "./FunctionToolConfig";
import type { OpenAICustomTool } from "./OpenAICustomTool";
import type { ProviderTool } from "./ProviderTool";
import type { ToolChoice } from "./ToolChoice";

/**
 * Contains all information required to tell an LLM what tools it can call
 * and what sorts of tool calls (parallel, none, etc) it is allowed to respond with.
 * Most inference providers can convert this into their desired tool format.
 */
export type ToolCallConfig = {
  static_tools_available: Array<FunctionToolConfig>;
  dynamic_tools_available: Array<FunctionToolConfig>;
  provider_tools: Array<ProviderTool>;
  openai_custom_tools: Array<OpenAICustomTool>;
  tool_choice: ToolChoice;
  parallel_tool_calls: boolean | null;
  allowed_tools: AllowedTools;
};
