// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TypescriptJudgeOptimize } from "./TypescriptJudgeOptimize";
import type { TypescriptJudgeOutputType } from "./TypescriptJudgeOutputType";

export type TypescriptJudgeConfig = {
  typescript_code: string;
  output_type: TypescriptJudgeOutputType;
  optimize: TypescriptJudgeOptimize;
};
