// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvaluationConfig } from "./EvaluationConfig";
import type { FunctionConfig } from "./FunctionConfig";
import type { MetricConfig } from "./MetricConfig";
import type { StaticToolConfig } from "./StaticToolConfig";

/**
 * Response type for GET /internal/ui_config
 *
 * Contains only UI-safe fields from the gateway config, excluding sensitive
 * information like provider credentials, API keys, and internal settings.
 */
export type UiConfig = {
  functions: { [key in string]: FunctionConfig };
  metrics: { [key in string]: MetricConfig };
  tools: { [key in string]: StaticToolConfig };
  evaluations: { [key in string]: EvaluationConfig };
  model_names: Array<string>;
  config_hash: string;
  /**
   * Whether the gateway config was loaded from the database (as opposed to a file on disk).
   * Used by the UI to decide whether to show the config editor.
   */
  config_in_database: boolean;
  /**
   * Whether the gateway is enforcing API key authentication (`[gateway.auth] enabled = true`).
   * Used by the UI to decide whether routes that bypass the gateway (e.g. the API keys page)
   * must validate the caller's key themselves.
   */
  auth_enabled: boolean;
};
