// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedTomlPathData } from "./ResolvedTomlPathData";
import type { UninitializedExperimentationConfigWithNamespaces } from "./UninitializedExperimentationConfigWithNamespaces";
import type { UninitializedSchema } from "./UninitializedSchema";
import type { UninitializedVariantInfo } from "./UninitializedVariantInfo";

export type UninitializedFunctionConfigJson = {
  variants: { [key in string]: UninitializedVariantInfo };
  system_schema?: ResolvedTomlPathData;
  user_schema?: ResolvedTomlPathData;
  assistant_schema?: ResolvedTomlPathData;
  schemas: { [key in string]: UninitializedSchema };
  output_schema?: ResolvedTomlPathData;
  description?: string;
  experimentation?: UninitializedExperimentationConfigWithNamespaces;
};
