// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UninitializedEmbeddingProviderConfig } from "./UninitializedEmbeddingProviderConfig";

export type UninitializedEmbeddingModelConfig = {
  routing: Array<string>;
  providers: { [key in string]: UninitializedEmbeddingProviderConfig };
  timeout_ms?: bigint;
};
