// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutopilotConfig } from "./AutopilotConfig";
import type { ClickHouseConfig } from "./ClickHouseConfig";
import type { MetricConfig } from "./MetricConfig";
import type { PostgresConfig } from "./PostgresConfig";
import type { ProviderTypesConfig } from "./ProviderTypesConfig";
import type { StorageKind } from "./StorageKind";
import type { UninitializedEmbeddingModelConfig } from "./UninitializedEmbeddingModelConfig";
import type { UninitializedEvaluationConfig } from "./UninitializedEvaluationConfig";
import type { UninitializedEvaluatorConfig } from "./UninitializedEvaluatorConfig";
import type { UninitializedFunctionConfig } from "./UninitializedFunctionConfig";
import type { UninitializedGatewayConfig } from "./UninitializedGatewayConfig";
import type { UninitializedModelConfig } from "./UninitializedModelConfig";
import type { UninitializedOptimizerInfo } from "./UninitializedOptimizerInfo";
import type { UninitializedRateLimitingConfig } from "./UninitializedRateLimitingConfig";
import type { UninitializedToolConfig } from "./UninitializedToolConfig";

/**
 * This struct is used to deserialize the TOML config file
 * It does not contain the information that needs to be loaded from the filesystem
 * such as the JSON schemas for the functions and tools.
 * If should be used as part of the `Config::load` method only.
 *
 * This allows us to avoid using Option types to represent variables that are initialized after the
 * config is initially parsed.
 */
export type UninitializedConfig = {
  gateway: UninitializedGatewayConfig;
  clickhouse: ClickHouseConfig;
  postgres: PostgresConfig;
  rate_limiting: UninitializedRateLimitingConfig;
  object_storage?: StorageKind;
  models: { [key in string]: UninitializedModelConfig };
  embedding_models: { [key in string]: UninitializedEmbeddingModelConfig };
  functions: { [key in string]: UninitializedFunctionConfig };
  metrics: { [key in string]: MetricConfig };
  tools: { [key in string]: UninitializedToolConfig };
  evaluators: { [key in string]: UninitializedEvaluatorConfig };
  evaluations: { [key in string]: UninitializedEvaluationConfig };
  provider_types: ProviderTypesConfig;
  optimizers: { [key in string]: UninitializedOptimizerInfo };
  autopilot: AutopilotConfig;
};
