// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateDatapointRequest } from "./UpdateDatapointRequest";

/**
 * Combined request for updating datapoints that includes the dataset name.
 * In the HTTP API, `dataset_name` comes from the URL path, but tools and
 * embedded clients need it in a single request struct.
 */
export type UpdateDatapointsToolParams = {
  /**
   * The name of the dataset containing the datapoints to update.
   */
  dataset_name: string;
  /**
   * The datapoints to update.
   */
  datapoints: Array<UpdateDatapointRequest>;
};
