// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from validating editable config TOML.
 */
export type ValidateConfigTomlResponse = { valid: boolean, };
