// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for validating editable config TOML.
 */
export type ValidateConfigTomlRequest = {
  /**
   * Human-readable TOML config with path strings.
   */
  toml: string;
  /**
   * File-backed content referenced by the TOML, keyed by the path string in the TOML body.
   */
  path_contents: { [key in string]: string };
};
