// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Row returned from the get_function_throughput_by_variant query.
 */
export type VariantThroughput = {
  /**
   * Start datetime of the period in RFC 3339 format with milliseconds
   */
  period_start: string;
  variant_name: string;
  /**
   * Number of inferences for this (period, variant) combination
   */
  count: number;
};
