// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable error category for `WriteConfigToolOutput::Error`.
 *
 * Only covers cases the LLM can act on. Transport/server failures are
 * surfaced as `ToolError` instead and never reach this enum.
 */
export type WriteConfigErrorCode = "validation";
