"""
Auto-generated Python dataclasses from JSON schemas.

This file is generated from JSON schemas in the tensorzero-core crate.
Do not edit this file manually - it will be overwritten.

Generated from schemas in: tensorzero-core/schemas/

To regenerate, run:
    python generate_schema_types.py
"""

# generated by datamodel-codegen:
#   filename:  merged_schema.json

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Literal

Model = Any


class Detail(Enum):
    low = 'low'
    high = 'high'
    auto = 'auto'


@dataclass
class ToolCall:
    id: str
    name: str
    arguments: str


@dataclass
class FileUrl:
    url: str
    mime_type: str | None = None
    detail: Detail | None = None


@dataclass
class ObjectStorageFile:
    mime_type: str
    storage_path: str
    data: str
    source_url: str | None = None
    detail: Detail | None = None


@dataclass
class Base64FileMetadata:
    mime_type: str
    source_url: str | None = None
    detail: Detail | None = None


@dataclass
class ThoughtSummaryBlock1:
    text: str
    type: Literal['summary_text']


ThoughtSummaryBlock = ThoughtSummaryBlock1


@dataclass
class Thought:
    text: str | None = None
    signature: str | None = None
    """
    An optional signature - currently, this is only used with Anthropic,
    and is ignored by other providers.
    """
    summary: list[ThoughtSummaryBlock] | None = None
    field_internal_provider_type: str | None = None
    """
    When set, this 'Thought' block will only be used for providers
    matching this type (e.g. `anthropic`). Other providers will emit
    a warning and discard the block.
    """


@dataclass
class InferenceResponseToolCall:
    id: str
    """
    A Tool Call ID to match up with tool call responses. See #4058.
    """
    raw_name: str
    """
    The name of the tool to call, as generated by the model.
    """
    raw_arguments: str
    """
    The raw arguments JSON string of the tool to call, as generated by the model.
    """
    name: str | None = None
    """
    The name of the tool to call, validated against tool configs. If not present, it means the tool call was invalid.
    """
    arguments: Any | None = None
    """
    The arguments of the tool to call, validated against tool configs. If not present, it means the tool call arguments were invalid.
    """


@dataclass
class Tool:
    description: str
    parameters: Any
    name: str
    strict: bool | None = False


class ToolChoice1(Enum):
    none = 'none'
    auto = 'auto'
    required = 'required'


@dataclass
class ToolChoice2:
    specific: str


ToolChoice = ToolChoice1 | ToolChoice2


@dataclass
class ProviderToolScope1:
    model_name: str
    model_provider_name: str


ProviderToolScope = ProviderToolScope1 | None


@dataclass
class UrlFile:
    url: str
    mime_type: str | None = None
    detail: Detail | None = None


@dataclass
class Base64File:
    mime_type: str
    data: str
    source_url: str | None = None
    detail: Detail | None = None


@dataclass
class ObjectStoragePointer:
    mime_type: str
    storage_path: str
    source_url: str | None = None
    detail: Detail | None = None


@dataclass
class ObjectStorageError:
    mime_type: str
    storage_path: str
    source_url: str | None = None
    detail: Detail | None = None
    error: str | None = None


@dataclass
class Arguments:
    pass


class Role(Enum):
    user = 'user'
    assistant = 'assistant'


@dataclass
class InputMessageContent1:
    text: str
    type: Literal['text']


@dataclass
class InputMessageContent2:
    name: str
    arguments: Arguments
    type: Literal['template']


@dataclass
class InputMessageContent3(ToolCall):
    type: Literal['tool_call']


@dataclass
class InputMessageContent4(InferenceResponseToolCall):
    type: Literal['tool_call']


@dataclass
class InputMessageContent5:
    name: str
    result: str
    id: str
    type: Literal['tool_result']


@dataclass
class InputMessageContent6:
    value: str
    type: Literal['raw_text']


@dataclass
class InputMessageContent7:
    type: Literal['thought']
    text: str | None = None
    signature: str | None = None
    """
    An optional signature - currently, this is only used with Anthropic,
    and is ignored by other providers.
    """
    summary: list[ThoughtSummaryBlock] | None = None
    field_internal_provider_type: str | None = None
    """
    When set, this 'Thought' block will only be used for providers
    matching this type (e.g. `anthropic`). Other providers will emit
    a warning and discard the block.
    """


@dataclass
class InputMessageContent8(UrlFile):
    type: Literal['file']


@dataclass
class InputMessageContent9(Base64File):
    type: Literal['file']


@dataclass
class InputMessageContent10(ObjectStoragePointer):
    type: Literal['file']


@dataclass
class InputMessageContent11(ObjectStorageFile):
    type: Literal['file']


@dataclass
class InputMessageContent12(ObjectStorageError):
    type: Literal['file']


@dataclass
class InputMessageContent13:
    data: Any
    """
    The underlying content block to be passed to the model provider.
    """
    type: Literal['unknown']
    model_provider_name: str | None = None
    """
    A fully-qualified name specifying when this content block should
    be included in the model provider input.
    """


InputMessageContent = (
    InputMessageContent1
    | InputMessageContent2
    | InputMessageContent3
    | InputMessageContent4
    | InputMessageContent5
    | InputMessageContent6
    | InputMessageContent7
    | InputMessageContent8
    | InputMessageContent9
    | InputMessageContent10
    | InputMessageContent11
    | InputMessageContent12
    | InputMessageContent13
)


ToolCallWrapper = ToolCall | InferenceResponseToolCall


@dataclass
class File1:
    url: str
    file_type: Literal['url']
    mime_type: str | None = None
    detail: Detail | None = None


@dataclass
class File2:
    mime_type: str
    data: str
    file_type: Literal['base64']
    source_url: str | None = None
    detail: Detail | None = None


@dataclass
class File3:
    mime_type: str
    storage_path: str
    file_type: Literal['object_storage_pointer']
    source_url: str | None = None
    detail: Detail | None = None


@dataclass
class File4:
    mime_type: str
    storage_path: str
    data: str
    file_type: Literal['object_storage']
    source_url: str | None = None
    detail: Detail | None = None


@dataclass
class File5:
    mime_type: str
    storage_path: str
    file_type: Literal['object_storage_error']
    source_url: str | None = None
    detail: Detail | None = None
    error: str | None = None


File = File1 | File2 | File3 | File4 | File5


@dataclass
class NestedMetadata:
    key: str
    value: str


@dataclass
class ContentBlockChatOutput1:
    text: str
    type: Literal['text']


@dataclass
class ContentBlockChatOutput2:
    id: str
    """
    A Tool Call ID to match up with tool call responses. See #4058.
    """
    raw_name: str
    """
    The name of the tool to call, as generated by the model.
    """
    raw_arguments: str
    """
    The raw arguments JSON string of the tool to call, as generated by the model.
    """
    type: Literal['tool_call']
    name: str | None = None
    """
    The name of the tool to call, validated against tool configs. If not present, it means the tool call was invalid.
    """
    arguments: Any | None = None
    """
    The arguments of the tool to call, validated against tool configs. If not present, it means the tool call arguments were invalid.
    """


@dataclass
class ContentBlockChatOutput3:
    type: Literal['thought']
    text: str | None = None
    signature: str | None = None
    """
    An optional signature - currently, this is only used with Anthropic,
    and is ignored by other providers.
    """
    summary: list[ThoughtSummaryBlock] | None = None
    field_internal_provider_type: str | None = None
    """
    When set, this 'Thought' block will only be used for providers
    matching this type (e.g. `anthropic`). Other providers will emit
    a warning and discard the block.
    """


@dataclass
class ContentBlockChatOutput4:
    data: Any
    type: Literal['unknown']
    model_provider_name: str | None = None


ContentBlockChatOutput = (
    ContentBlockChatOutput1
    | ContentBlockChatOutput2
    | ContentBlockChatOutput3
    | ContentBlockChatOutput4
)


@dataclass
class DatapointMetadataUpdate:
    name: str | None = None
    """
    Datapoint name. If omitted, it will be left unchanged. If specified as `null`, it will be set to `null`. If specified as a value, it will be set to the provided value.
    """


@dataclass
class JsonDatapointOutputUpdate:
    raw: str
    """
    The raw output of the datapoint. For valid JSON outputs, this should be a JSON-serialized string.
    """


@dataclass
class ContentBlock1:
    text: str
    type: Literal['text']


@dataclass
class ContentBlock2:
    id: str
    name: str
    arguments: str
    type: Literal['tool_call']


@dataclass
class ContentBlock3:
    name: str
    result: str
    id: str
    type: Literal['tool_result']


@dataclass
class Url:
    file_url: FileUrl


@dataclass
class ContentBlock4:
    type: Literal['file']
    Url: Url


@dataclass
class ObjectStoragePointer1:
    metadata: Base64FileMetadata
    storage_path: str


@dataclass
class ContentBlock6:
    type: Literal['file']
    ObjectStoragePointer: ObjectStoragePointer1


@dataclass
class ContentBlock7:
    type: Literal['file']
    ObjectStorage: ObjectStorageFile


@dataclass
class ContentBlock8:
    type: Literal['thought']
    text: str | None = None
    signature: str | None = None
    """
    An optional signature - currently, this is only used with Anthropic,
    and is ignored by other providers.
    """
    summary: list[ThoughtSummaryBlock] | None = None
    field_internal_provider_type: str | None = None
    """
    When set, this 'Thought' block will only be used for providers
    matching this type (e.g. `anthropic`). Other providers will emit
    a warning and discard the block.
    """


@dataclass
class ContentBlock9:
    data: Any
    """
    The underlying content block to be passed to the model provider.
    """
    type: Literal['unknown']
    model_provider_name: str | None = None
    """
    A fully-qualified name specifying when this content block should
    be included in the model provider input.
    E.g `tensorzero::model_name::claude-3-7-sonnet-20250219-thinking::provider_name::anthropic-extra-body`

    If set to `Some`, this is compared against the output of `fully_qualified_name` before invoking
    a model provider, and stripped from the input if it doesn't match.
    If set to `None, then this is passed to all model providers.
    Individual model provider implementation never need to check this field themselves -
    they only need to produce it with the proper `fully_qualified_name` set.
    """


@dataclass
class DoubleOptionalExample:
    simple_optional: str | None = None
    """
    A regular optional field (single Option)
    """
    double_optional: str | None = None
    """
    A double-optional field with custom annotation

    The outer Option represents "field may be absent"
    The inner Option represents "field may be explicitly null"

    Custom annotation "x-double-optional" marks this for special handling
    """
    annotated_field: int | None = None
    """
    Another double-optional with multiple custom annotations
    """


@dataclass
class LazyFile1:
    Url: Url


@dataclass
class LazyFile3:
    ObjectStoragePointer: ObjectStoragePointer1


@dataclass
class LazyFile4:
    ObjectStorage: ObjectStorageFile


@dataclass
class NestedOptionalExample:
    name: str
    metadata: NestedMetadata | None = None


@dataclass
class RawText:
    value: str


@dataclass
class Template:
    name: str
    arguments: Arguments


@dataclass
class Text:
    text: str


@dataclass
class ToolCallChunk:
    id: str
    raw_arguments: str
    raw_name: str | None = None


@dataclass
class ToolResult:
    name: str
    result: str
    id: str


@dataclass
class TransformExample:
    regular_field: str
    double_optional_field: bool | None = None


@dataclass
class Unknown:
    data: Any
    """
    The underlying content block to be passed to the model provider.
    """
    model_provider_name: str | None = None
    """
    A fully-qualified name specifying when this content block should
    be included in the model provider input.
    """


@dataclass
class UpdateDatapointsResponse:
    ids: list[str]
    """
    The IDs of the datapoints that were updated.
    These are newly generated IDs for UpdateDatapoint requests, and they are the same IDs for UpdateDatapointMetadata requests.
    """


PendingObjectStoreFile = ObjectStorageFile


@dataclass
class ProviderTool:
    tool: Any
    scope: ProviderToolScope | None = None


System = str | Arguments


@dataclass
class InputMessage:
    role: Role
    content: list[InputMessageContent]


@dataclass
class Input:
    system: System | None = None
    messages: list[InputMessage] | None = field(default_factory=lambda: [])


@dataclass
class DynamicToolParams:
    allowed_tools: list[str] | None = None
    """
    A subset of static tools configured for the function that the inference is allowed to use. Optional.
    If not provided, all static tools are allowed.
    """
    additional_tools: list[Tool] | None = None
    """
    Tools that the user provided at inference time (not in function config), in addition to the function-configured
    tools, that are also allowed.
    """
    tool_choice: ToolChoice | None = None
    """
    User-specified tool choice strategy. If provided during inference, it will override the function-configured tool choice.
    Optional.
    """
    parallel_tool_calls: bool | None = None
    """
    Whether to use parallel tool calls in the inference. Optional.
    If provided during inference, it will override the function-configured parallel tool calls.
    """
    provider_tools: list[ProviderTool] | None = None
    """
    Provider-specific tool configurations (not persisted to database)
    """


@dataclass
class UpdateChatDatapointRequest:
    id: str
    """
    The ID of the datapoint to update. Required.
    """
    input: Input | None = None
    """
    Datapoint input. If omitted, it will be left unchanged.
    """
    output: list[ContentBlockChatOutput] | None = None
    """
    Chat datapoint output. If omitted, it will be left unchanged. If empty, it will be cleared. Otherwise,
    it will overwrite the existing output.
    """
    tool_params: DynamicToolParams | None = None
    """
    Datapoint tool parameters. If omitted, it will be left unchanged. If specified as `null`, it will be set to `null`. If specified as a value, it will be set to the provided value.
    """
    tags: dict[str, Any] | None = None
    """
    Datapoint tags. If omitted, it will be left unchanged. If empty, it will be cleared. Otherwise,
    it will be overwrite the existing tags.
    """
    metadata: DatapointMetadataUpdate | None = None
    """
    Metadata fields. If omitted, it will be left unchanged.
    """


@dataclass
class UpdateJsonDatapointRequest:
    id: str
    """
    The ID of the datapoint to update. Required.
    """
    input: Input | None = None
    """
    Datapoint input. If omitted, it will be left unchanged.
    """
    output: JsonDatapointOutputUpdate | None = None
    """
    JSON datapoint output. If omitted, it will be left unchanged. If `null`, it will be set to `null`. If specified as a value, it will be set to the provided value.
    This will be parsed and validated against output_schema, and valid `raw` values will be parsed and stored as `parsed`. Invalid `raw` values will
    also be stored, because we allow invalid outputs in datapoints by design.
    """
    output_schema: Any | None = None
    """
    The output schema of the JSON datapoint. If omitted, it will be left unchanged. If specified as `null`, it will be set to `null`. If specified as a value, it will be set to the provided value.
    If not provided, the function's output schema will be used.
    """
    tags: dict[str, Any] | None = None
    """
    Datapoint tags. If omitted, it will be left unchanged. If empty, it will be cleared. Otherwise,
    it will be overwrite the existing tags.
    """
    metadata: DatapointMetadataUpdate | None = None
    """
    Metadata fields. If omitted, it will be left unchanged.
    """


@dataclass
class UpdateDatapointRequest1:
    id: str
    """
    The ID of the datapoint to update. Required.
    """
    type: Literal['chat']
    input: Input | None = None
    """
    Datapoint input. If omitted, it will be left unchanged.
    """
    output: list[ContentBlockChatOutput] | None = None
    """
    Chat datapoint output. If omitted, it will be left unchanged. If empty, it will be cleared. Otherwise,
    it will overwrite the existing output.
    """
    tool_params: DynamicToolParams | None = None
    """
    Datapoint tool parameters. If omitted, it will be left unchanged. If specified as `null`, it will be set to `null`. If specified as a value, it will be set to the provided value.
    """
    tags: dict[str, Any] | None = None
    """
    Datapoint tags. If omitted, it will be left unchanged. If empty, it will be cleared. Otherwise,
    it will be overwrite the existing tags.
    """
    metadata: DatapointMetadataUpdate | None = None
    """
    Metadata fields. If omitted, it will be left unchanged.
    """


@dataclass
class UpdateDatapointRequest2:
    id: str
    """
    The ID of the datapoint to update. Required.
    """
    type: Literal['json']
    input: Input | None = None
    """
    Datapoint input. If omitted, it will be left unchanged.
    """
    output: JsonDatapointOutputUpdate | None = None
    """
    JSON datapoint output. If omitted, it will be left unchanged. If `null`, it will be set to `null`. If specified as a value, it will be set to the provided value.
    This will be parsed and validated against output_schema, and valid `raw` values will be parsed and stored as `parsed`. Invalid `raw` values will
    also be stored, because we allow invalid outputs in datapoints by design.
    """
    output_schema: Any | None = None
    """
    The output schema of the JSON datapoint. If omitted, it will be left unchanged. If specified as `null`, it will be set to `null`. If specified as a value, it will be set to the provided value.
    If not provided, the function's output schema will be used.
    """
    tags: dict[str, Any] | None = None
    """
    Datapoint tags. If omitted, it will be left unchanged. If empty, it will be cleared. Otherwise,
    it will be overwrite the existing tags.
    """
    metadata: DatapointMetadataUpdate | None = None
    """
    Metadata fields. If omitted, it will be left unchanged.
    """


UpdateDatapointRequest = UpdateDatapointRequest1 | UpdateDatapointRequest2


@dataclass
class ContentBlock5:
    type: Literal['file']
    Base64: PendingObjectStoreFile


ContentBlock = (
    ContentBlock1
    | ContentBlock2
    | ContentBlock3
    | ContentBlock4
    | ContentBlock5
    | ContentBlock6
    | ContentBlock7
    | ContentBlock8
    | ContentBlock9
)


@dataclass
class LazyFile2:
    Base64: PendingObjectStoreFile


LazyFile = LazyFile1 | LazyFile2 | LazyFile3 | LazyFile4


@dataclass
class UpdateDatapointsRequest:
    datapoints: list[UpdateDatapointRequest]
    """
    The datapoints to update.
    """
