"""
Auto-generated Python dataclasses from JSON schemas.

This file is generated from JSON schemas in the tensorzero-core crate.
Do not edit this file manually - it will be overwritten.

Generated from schemas in: tensorzero-core/clients/schemas/

To regenerate, run:
    python generate_schema_types.py
"""

from __future__ import annotations


class UnsetType:
    """Sentinel value to distinguish between omitted fields and null values."""

    def __repr__(self):
        return "UNSET"


UNSET = UnsetType()
"""
Sentinel value to distinguish between omitted and null in API requests.

Usage:
- UNSET: Field is omitted (don't change existing value)
- None: Field is explicitly set to null
- value: Field is set to the provided value

Example:
    # Omit the field entirely (don't update it)
    update = UpdateRequest(name=UNSET)

    # Set the field to null (clear the existing value)
    update = UpdateRequest(name=None)

    # Set the field to a value
    update = UpdateRequest(name="new_value")
"""
