//! Shared types for TensorZero Autopilot tools.

use std::collections::HashMap;

use durable_tools::SideInfo;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::tools::OptimizationWorkflowSideInfo;

/// Side information required for autopilot client tools.
///
/// This should contain all IDs that might be needed as input to a tool
/// that do not need to be generated by LLMs (like the session id or a config hash).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AutopilotSideInfo {
    /// The event ID of the ToolCall event (for correlating ToolResult).
    pub tool_call_event_id: Uuid,

    /// The session ID for this autopilot session.
    pub session_id: Uuid,

    /// An optional hash of the current configuration.
    /// Set if you would like to start from a particular config for a tool call.
    pub config_snapshot_hash: Option<String>,

    /// Settings for optimization workflows run on the gateway by autopilot.
    pub optimization: OptimizationWorkflowSideInfo,
}

impl SideInfo for AutopilotSideInfo {}

impl AutopilotSideInfo {
    pub fn to_tags(&self) -> HashMap<String, String> {
        let mut tags = HashMap::new();
        tags.insert(
            "tensorzero::autopilot::tool_call_event_id".to_string(),
            self.tool_call_event_id.to_string(),
        );
        tags.insert(
            "tensorzero::autopilot::session_id".to_string(),
            self.session_id.to_string(),
        );
        if let Some(config_hash) = &self.config_snapshot_hash {
            tags.insert(
                "tensorzero::autopilot::config_snapshot_hash".to_string(),
                config_hash.clone(),
            );
        }
        tags
    }
}

impl TryFrom<AutopilotSideInfo> for () {
    type Error = anyhow::Error;

    fn try_from(_: AutopilotSideInfo) -> Result<Self, Self::Error> {
        Ok(())
    }
}
