"""
Auto-generated Python dataclasses from JSON schemas.

This file is generated from JSON schemas in the tensorzero-core crate.
Do not edit this file manually - it will be overwritten.

Generated from schemas in: tensorzero-core/clients/schemas/

To regenerate, run:
    python generate_schema_types.py
"""


class UnsetType:
    """Sentinel value to distinguish between omitted fields and null values."""

    def __repr__(self):
        return "UNSET"


UNSET = UnsetType()
"""
Sentinel value to distinguish between omitted and null in API requests.

Usage:
- UNSET: Field is omitted (don't change existing value)
- None: Field is explicitly set to null
- value: Field is set to the provided value

Example:
    # Omit the field entirely (don't update it)
    update = UpdateRequest(name=UNSET)

    # Set the field to null (clear the existing value)
    update = UpdateRequest(name=None)

    # Set the field to a value
    update = UpdateRequest(name="new_value")
"""


from dataclasses import dataclass, field
from typing import Any, Literal

Model = Any


Detail = Literal['low', 'high', 'auto']


@dataclass(kw_only=True)
class InferenceResponseToolCall:
    id: str
    """
    A Tool Call ID to match up with tool call responses. See #4058.
    """
    raw_name: str
    """
    The name of the tool to call, as generated by the model.
    """
    raw_arguments: str
    """
    The raw arguments JSON string of the tool to call, as generated by the model.
    """
    name: str | None = None
    """
    The name of the tool to call, validated against tool configs. If not present, it means the tool call was invalid.
    """
    arguments: Any | None = None
    """
    The arguments of the tool to call, validated against tool configs. If not present, it means the tool call arguments were invalid.
    """


@dataclass(kw_only=True)
class ThoughtSummaryBlockSummaryText:
    text: str
    type: Literal['summary_text']


ThoughtSummaryBlock = ThoughtSummaryBlockSummaryText


@dataclass(kw_only=True)
class Thought:
    text: str | None = None
    signature: str | None = None
    """
    An optional signature - currently, this is only used with Anthropic,
    and is ignored by other providers.
    """
    summary: list[ThoughtSummaryBlock] | None = None
    field_internal_provider_type: str | None = None
    """
    When set, this 'Thought' block will only be used for providers
    matching this type (e.g. `anthropic`). Other providers will emit
    a warning and discard the block.
    """


@dataclass(kw_only=True)
class Tool:
    description: str
    parameters: Any
    name: str
    strict: bool | None = False


@dataclass(kw_only=True)
class ToolChoice1:
    specific: str


ToolChoice = Literal['none', 'auto', 'required'] | ToolChoice1


@dataclass(kw_only=True)
class ProviderToolScope1:
    model_name: str
    model_provider_name: str


ProviderToolScope = ProviderToolScope1 | None


@dataclass(kw_only=True)
class UrlFile:
    url: str
    mime_type: str | None = None
    detail: Detail | None = None


@dataclass(kw_only=True)
class Base64File:
    mime_type: str
    data: str
    source_url: str | None = None
    detail: Detail | None = None


@dataclass(kw_only=True)
class StorageKindS3Compatible:
    type: Literal['s3_compatible']
    bucket_name: str | None = None
    region: str | None = None
    endpoint: str | None = None
    allow_http: bool | None = None
    prefix: str | None = ''
    """
    An extra prefix to prepend to the object key.
    This is only enabled in e2e tests, to prevent clashes between concurrent test runs.
    """


@dataclass(kw_only=True)
class StorageKindFilesystem:
    path: str
    type: Literal['filesystem']


@dataclass(kw_only=True)
class StorageKindDisabled:
    type: Literal['disabled']


StorageKind = StorageKindS3Compatible | StorageKindFilesystem | StorageKindDisabled


@dataclass(kw_only=True)
class Arguments:
    pass


Role = Literal['user', 'assistant']


@dataclass(kw_only=True)
class InputMessageContentText:
    text: str
    type: Literal['text']


@dataclass(kw_only=True)
class InputMessageContentTemplate:
    name: str
    arguments: Arguments
    type: Literal['template']


@dataclass(kw_only=True)
class InputMessageContentToolResult:
    name: str
    result: str
    id: str
    type: Literal['tool_result']


@dataclass(kw_only=True)
class InputMessageContentRawText:
    value: str
    type: Literal['raw_text']


@dataclass(kw_only=True)
class InputMessageContentThought(Thought):
    type: Literal['thought']


@dataclass(kw_only=True)
class InputMessageContentUnknown:
    data: Any
    """
    The underlying content block to be passed to the model provider.
    """
    type: Literal['unknown']
    model_provider_name: str | None = None
    """
    A fully-qualified name specifying when this content block should
    be included in the model provider input.
    """


@dataclass(kw_only=True)
class ToolCall:
    id: str
    name: str
    arguments: str


ToolCallWrapper = ToolCall | InferenceResponseToolCall


@dataclass(kw_only=True)
class File1(UrlFile):
    file_type: Literal['url']


@dataclass(kw_only=True)
class File2(Base64File):
    file_type: Literal['base64']


@dataclass(kw_only=True)
class ContentBlockChatOutput1:
    text: str
    type: Literal['text']


@dataclass(kw_only=True)
class ContentBlockChatOutput2(InferenceResponseToolCall):
    type: Literal['tool_call']


@dataclass(kw_only=True)
class ContentBlockChatOutput3(Thought):
    type: Literal['thought']


@dataclass(kw_only=True)
class ContentBlockChatOutput4:
    data: Any
    type: Literal['unknown']
    model_provider_name: str | None = None


ContentBlockChatOutput = (
    ContentBlockChatOutput1
    | ContentBlockChatOutput2
    | ContentBlockChatOutput3
    | ContentBlockChatOutput4
)


@dataclass(kw_only=True)
class DatapointMetadataUpdate:
    name: str | None | UnsetType = UNSET
    """
    Datapoint name. If omitted, it will be left unchanged. If specified as `null`, it will be set to `null`. If specified as a value, it will be set to the provided value.
    """


@dataclass(kw_only=True)
class JsonDatapointOutputUpdate:
    raw: str
    """
    The raw output of the datapoint. For valid JSON outputs, this should be a JSON-serialized string.
    """


@dataclass(kw_only=True)
class RawText:
    value: str


@dataclass(kw_only=True)
class Template:
    name: str
    arguments: Arguments


@dataclass(kw_only=True)
class Text:
    text: str


@dataclass(kw_only=True)
class ToolResult:
    name: str
    result: str
    id: str


@dataclass(kw_only=True)
class Unknown:
    data: Any
    """
    The underlying content block to be passed to the model provider.
    """
    model_provider_name: str | None = None
    """
    A fully-qualified name specifying when this content block should
    be included in the model provider input.
    """


@dataclass(kw_only=True)
class UpdateDatapointsResponse:
    ids: list[str]
    """
    The IDs of the datapoints that were updated.
    These are newly generated IDs for UpdateDatapoint requests, and they are the same IDs for UpdateDatapointMetadata requests.
    """


@dataclass(kw_only=True)
class ProviderTool:
    tool: Any
    scope: ProviderToolScope | None = None


@dataclass(kw_only=True)
class StoragePath:
    kind: StorageKind
    path: str


@dataclass(kw_only=True)
class ObjectStoragePointer:
    mime_type: str
    storage_path: StoragePath
    source_url: str | None = None
    detail: Detail | None = None


@dataclass(kw_only=True)
class ObjectStorageFile:
    mime_type: str
    storage_path: StoragePath
    data: str
    source_url: str | None = None
    detail: Detail | None = None


@dataclass(kw_only=True)
class ObjectStorageError:
    mime_type: str
    storage_path: StoragePath
    source_url: str | None = None
    detail: Detail | None = None
    error: str | None = None


System = str | Arguments


@dataclass(kw_only=True)
class InputMessageContentToolCall:
    type: Literal['tool_call']


@dataclass(kw_only=True)
class File3(ObjectStoragePointer):
    file_type: Literal['object_storage_pointer']


@dataclass(kw_only=True)
class File4(ObjectStorageFile):
    file_type: Literal['object_storage']


@dataclass(kw_only=True)
class File5(ObjectStorageError):
    file_type: Literal['object_storage_error']


File = File1 | File2 | File3 | File4 | File5


@dataclass(kw_only=True)
class DynamicToolParams:
    allowed_tools: list[str] | None = None
    """
    A subset of static tools configured for the function that the inference is allowed to use. Optional.
    If not provided, all static tools are allowed.
    """
    additional_tools: list[Tool] | None = None
    """
    Tools that the user provided at inference time (not in function config), in addition to the function-configured
    tools, that are also allowed.
    """
    tool_choice: ToolChoice | None = None
    """
    User-specified tool choice strategy. If provided during inference, it will override the function-configured tool choice.
    Optional.
    """
    parallel_tool_calls: bool | None = None
    """
    Whether to use parallel tool calls in the inference. Optional.
    If provided during inference, it will override the function-configured parallel tool calls.
    """
    provider_tools: list[ProviderTool] | None = None
    """
    Provider-specific tool configurations (not persisted to database)
    """


@dataclass(kw_only=True)
class InputMessageContentFile:
    type: Literal['file']


InputMessageContent = (
    InputMessageContentText
    | InputMessageContentTemplate
    | InputMessageContentToolCall
    | InputMessageContentToolResult
    | InputMessageContentRawText
    | InputMessageContentThought
    | InputMessageContentFile
    | InputMessageContentUnknown
)


@dataclass(kw_only=True)
class InputMessage:
    role: Role
    content: list[InputMessageContent]


@dataclass(kw_only=True)
class Input:
    system: System | None = None
    messages: list[InputMessage] | None = field(default_factory=lambda: [])


@dataclass(kw_only=True)
class UpdateChatDatapointRequestInternal:
    id: str
    """
    The ID of the datapoint to update. Required.
    """
    input: Input | None = None
    """
    Datapoint input. If omitted, it will be left unchanged.
    """
    output: list[ContentBlockChatOutput] | None = None
    """
    Chat datapoint output. If omitted, it will be left unchanged. If empty, it will be cleared. Otherwise,
    it will overwrite the existing output.
    """
    tool_params: DynamicToolParams | None | UnsetType = UNSET
    """
    Datapoint tool parameters. If omitted, it will be left unchanged. If specified as `null`, it will be set to `null`. If specified as a value, it will be set to the provided value.
    """
    tags: dict[str, Any] | None = None
    """
    Datapoint tags. If omitted, it will be left unchanged. If empty, it will be cleared. Otherwise,
    it will be overwrite the existing tags.
    """
    metadata: DatapointMetadataUpdate | None = None
    """
    Metadata fields. If omitted, it will be left unchanged.
    """


@dataclass(kw_only=True)
class UpdateJsonDatapointRequestInternal:
    id: str
    """
    The ID of the datapoint to update. Required.
    """
    input: Input | None = None
    """
    Datapoint input. If omitted, it will be left unchanged.
    """
    output: JsonDatapointOutputUpdate | None | UnsetType = UNSET
    """
    JSON datapoint output. If omitted, it will be left unchanged. If `null`, it will be set to `null`. If specified as a value, it will be set to the provided value.
    This will be parsed and validated against output_schema, and valid `raw` values will be parsed and stored as `parsed`. Invalid `raw` values will
    also be stored, because we allow invalid outputs in datapoints by design.
    """
    output_schema: Any | None = None
    """
    The output schema of the JSON datapoint. If omitted, it will be left unchanged. If specified as `null`, it will be set to `null`. If specified as a value, it will be set to the provided value.
    If not provided, the function's output schema will be used.
    """
    tags: dict[str, Any] | None = None
    """
    Datapoint tags. If omitted, it will be left unchanged. If empty, it will be cleared. Otherwise,
    it will be overwrite the existing tags.
    """
    metadata: DatapointMetadataUpdate | None = None
    """
    Metadata fields. If omitted, it will be left unchanged.
    """


@dataclass(kw_only=True)
class UpdateChatDatapointRequest(UpdateChatDatapointRequestInternal):
    type: Literal['chat']


@dataclass(kw_only=True)
class UpdateJsonDatapointRequest(UpdateJsonDatapointRequestInternal):
    type: Literal['json']


UpdateDatapointRequest = UpdateChatDatapointRequest | UpdateJsonDatapointRequest


@dataclass(kw_only=True)
class UpdateDatapointsRequest:
    datapoints: list[UpdateDatapointRequest]
    """
    The datapoints to update.
    """
