// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CredentialLocation =
  | { Env: string }
  | { PathFromEnv: string }
  | { Dynamic: string }
  | { Path: string }
  | "Sdk"
  | "None";
