// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventPayloadMessageContent } from "./EventPayloadMessageContent";
import type { Role } from "./Role";

/**
 * A message payload specific to autopilot events.
 * Content is restricted to Text blocks only.
 */
export type EventPayloadMessage = {
  role: Role;
  content: Array<EventPayloadMessageContent>;
};
