// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableBounds } from "./TableBounds";

export type FeedbackBoundsByType = {
  boolean: TableBounds;
  float: TableBounds;
  comment: TableBounds;
  demonstration: TableBounds;
};
