// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Base64File } from "./Base64File";
import type { ObjectStorageError } from "./ObjectStorageError";
import type { ObjectStorageFile } from "./ObjectStorageFile";
import type { ObjectStoragePointer } from "./ObjectStoragePointer";
import type { UrlFile } from "./UrlFile";

/**
 * A file for an inference or a datapoint.
 */
export type File =
  | ({ file_type: "url" } & UrlFile)
  | ({ file_type: "base64" } & Base64File)
  | ({ file_type: "object_storage_pointer" } & ObjectStoragePointer)
  | ({ file_type: "object_storage" } & ObjectStorageFile)
  | ({ file_type: "object_storage_error" } & ObjectStorageError);
