// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Initialized GCP Vertex Gemini SFT Config (per-job settings only).
 * Provider-level settings (project_id, region, bucket_name, credentials, etc.)
 * come from `provider_types.gcp_vertex_gemini.sft` in the gateway config.
 */
export type GCPVertexGeminiSFTConfig = {
  model: string;
  learning_rate_multiplier?: number;
  adapter_size?: number;
  n_epochs?: number;
  export_last_checkpoint_only?: boolean;
  seed?: bigint;
  tuned_model_display_name?: string;
};
