// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An option in a multiple choice question.
 */
export type MultipleChoiceOption = {
  id: string;
  /**
   * The display text for this option that the user will see and select. Should be concise (1-5 words).
   */
  label: string;
  /**
   * Explanation of what this option means or what will happen if chosen.
   */
  description: string;
};
