// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenAIGrammarSyntax } from "./OpenAIGrammarSyntax";

export type OpenAIGrammarDefinition = {
  syntax: OpenAIGrammarSyntax;
  definition: string;
};
