// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonStreamingTimeouts } from "./NonStreamingTimeouts";
import type { StreamingTimeouts } from "./StreamingTimeouts";

/**
 * Configures the timeouts for both streaming and non-streaming requests.
 * This can be attached to various other configs (e.g. variants, models, model providers)
 */
export type TimeoutsConfig = {
  non_streaming: NonStreamingTimeouts;
  streaming: StreamingTimeouts;
};
