// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TogetherBatchSizeDescription } from "./TogetherBatchSizeDescription";

export type TogetherBatchSize = number | TogetherBatchSizeDescription;
