// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonMode } from "./JsonMode";
import type { ResolvedTomlPathData } from "./ResolvedTomlPathData";
import type { RetryConfig } from "./RetryConfig";

export type UninitializedDiclConfig = {
  weight: number | null;
  embedding_model: string;
  k: number;
  model: string;
  system_instructions: ResolvedTomlPathData | null;
  temperature: number | null;
  top_p: number | null;
  stop_sequences: Array<string> | null;
  presence_penalty: number | null;
  frequency_penalty: number | null;
  max_tokens: number | null;
  seed: number | null;
  reasoning_effort?: string;
  thinking_budget_tokens?: number;
  verbosity?: string;
  json_mode: JsonMode | null;
  retries: RetryConfig;
  max_distance: number | null;
};
