// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateDatapointMetadataRequest } from "./UpdateDatapointMetadataRequest";

/**
 * Request to update metadata for one or more datapoints in a dataset.
 * Used by the `PATCH /v1/datasets/{dataset_id}/datapoints/metadata` endpoint.
 */
export type UpdateDatapointsMetadataRequest = {
  /**
   * The datapoints to update metadata for.
   */
  datapoints: Array<UpdateDatapointMetadataRequest>;
};
