use serde::Serialize;
use serde_json::Value as JsonValue;
use tensorzero_derive::TensorZeroDeserialize;
use thiserror::Error;

/// Serializable error type for tool execution.
///
/// This enum contains framework-level errors generated by durable-tools itself,
/// plus a `User` variant for tool-specific errors. Tool implementations should
/// define their own error types and convert them to `NonControlToolError::User`.
#[cfg_attr(feature = "ts-bindings", derive(ts_rs::TS))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[derive(Debug, Clone, Error, Serialize, TensorZeroDeserialize)]
#[serde(tag = "kind")]
#[serde(rename_all = "snake_case")]
#[cfg_attr(feature = "ts-bindings", ts(export))]
pub enum NonControlToolError {
    /// Step error.
    #[error("Step error: {base_name}: {error}")]
    Step { base_name: String, error: String },

    /// Serialization error.
    #[error("Serialization error: {message}")]
    Serialization { message: String },

    /// Task panic error.
    #[error("Task panicked: {message}")]
    TaskPanicked { message: String },

    /// Tool was not found in the registry.
    #[error("Tool not found: {name}")]
    ToolNotFound { name: String },

    /// Tool with this name is already registered.
    #[error("Tool '{name}' is already registered. Each tool name must be unique.")]
    DuplicateToolName { name: String },

    /// Parameter validation or parsing failed.
    #[error("Parameter error: {message}")]
    InvalidParams { message: String },

    /// Schema generation failed.
    #[error("Schema generation failed: {message}")]
    SchemaGeneration { message: String },

    /// Operation timed out.
    #[error("Timed out waiting for '{step_name}'")]
    Timeout { step_name: String },

    /// Validation error.
    #[error("Validation error: {message}")]
    Validation { message: String },

    /// Internal task error.
    #[error("Internal error: {message}")]
    Internal { message: String },

    /// Child task failed.
    #[error("Child task failed at '{step_name}': {message}")]
    ChildFailed { step_name: String, message: String },

    /// Child task was cancelled.
    #[error("Child task was cancelled at '{step_name}'")]
    ChildCancelled { step_name: String },

    /// Invalid durable configuration.
    #[error("Invalid configuration: {reason}")]
    InvalidConfiguration { reason: String },

    /// Reserved header prefix used.
    #[error("Header key '{key}' uses reserved prefix 'durable::'")]
    ReservedHeaderPrefix { key: String },

    /// Invalid event name.
    #[error("Invalid event name: {reason}")]
    InvalidEventName { reason: String },

    /// User-defined error from tool implementation.
    ///
    /// Tool implementations should define their own error types and convert
    /// them to this variant. The `error_data` field stores structured JSON
    /// that can be deserialized back to the original error type.
    #[error("{message}")]
    User {
        /// Human-readable error message.
        message: String,
        /// Structured error data for persistence and later retrieval.
        error_data: JsonValue,
    },

    //// Error occurred while trying to spawn a subtask
    #[error("failed to spawn subtask `{name}`: {error}")]
    SubtaskSpawnFailed { name: String, error: String },

    /// Error occurred while trying to emit an event.
    #[error("failed to emit event `{event_name}`: {error}")]
    EmitEventFailed { event_name: String, error: String },
}

/// The type written in `ToolOutcome::Failure` for tool errors.
#[cfg_attr(feature = "ts-bindings", derive(ts_rs::TS))]
#[cfg_attr(feature = "openapi", derive(utoipa::ToSchema))]
#[derive(Debug, Clone, Serialize, TensorZeroDeserialize)]
#[serde(rename_all = "snake_case")]
#[serde(tag = "kind")]
#[cfg_attr(feature = "ts-bindings", ts(export))]
pub enum ToolFailure {
    Control { message: String },
    Tool { error: NonControlToolError },
    Database { message: String },
}
