// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type AnthropicProvider = {
  model_name: string;
  api_base: string | null;
  provider_tools: Array<JsonValue>;
};
