// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A newtype wrapper around Map<String, Value> for template and system arguments
 */
export type Arguments = { [key in string]?: JsonValue };
