// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for the autopilot status endpoint.
 *
 * Indicates whether the autopilot client is configured (i.e., whether
 * `TENSORZERO_AUTOPILOT_API_KEY` is set).
 */
export type AutopilotStatusResponse = { enabled: boolean };
