// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptimizationWorkflowSideInfo } from "./OptimizationWorkflowSideInfo";

/**
 * Side information required for autopilot client tools.
 *
 * This should contain all IDs that might be needed as input to a tool
 * that do not need to be generated by LLMs (like the session id or a config hash).
 * We should implement this as a type that has optional or mandatory fields as needed
 * for each kind of tool, then implement TryFrom<AutopilotSideInfo> for each tool's side info type.
 * This can fail if the correct information is not present.
 */
export type AutopilotSideInfo = {
  /**
   * The event ID of the ToolCall event (for correlating ToolResult).
   */
  tool_call_event_id: string;
  /**
   * The session ID for this autopilot session.
   */
  session_id: string;
  /**
   * A hash of the current configuration.
   */
  config_snapshot_hash: string;
  /**
   * Settings for optimization workflows run on the gateway by autopilot.
   */
  optimization: OptimizationWorkflowSideInfo;
};
