// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Like `Base64File`, but without the data field.
 */
export type Base64FileMetadata = { url: string | null; mime_type: string };
