// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BaseModelTable<T> = {
  table: { [key in string]?: T };
  global_outbound_http_timeout: [number, number];
};
