// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BatchConfig = {
  input_uri_prefix: string;
  output_uri_prefix: string;
  batch_request_url: string;
};
