// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BatchWritesConfig = {
  enabled: boolean;
  flush_interval_ms: bigint;
  max_rows: number;
};
