// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BestOfNEvaluatorConfig } from "./BestOfNEvaluatorConfig";

export type BestOfNSamplingConfig = {
  weight?: number;
  candidates: Array<string>;
  evaluator: BestOfNEvaluatorConfig;
};
