// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtraBodyConfig } from "./ExtraBodyConfig";
import type { ExtraHeadersConfig } from "./ExtraHeadersConfig";
import type { JsonMode } from "./JsonMode";
import type { PathWithContents } from "./PathWithContents";
import type { RetryConfig } from "./RetryConfig";

export type ChainOfThoughtConfig = { weight: number | null, model: string, system_template: PathWithContents | null, user_template: PathWithContents | null, assistant_template: PathWithContents | null, temperature: number | null, top_p: number | null, max_tokens: number | null, presence_penalty: number | null, frequency_penalty: number | null, seed: number | null, stop_sequences: Array<string> | null, json_mode: JsonMode | null, retries: RetryConfig, extra_body: ExtraBodyConfig | null, extra_headers: ExtraHeadersConfig | null, };
