// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JSONSchema } from "./JSONSchema";
import type { PathWithContents } from "./PathWithContents";

/**
 * Holds of all of the templates and schemas used by a chat-completion variant.
 */
export type ChatTemplates = {
  [key in string]?: {
    template: PathWithContents;
    schema: JSONSchema | null;
    legacy_definition: boolean;
  };
};
