// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlockChatOutput } from "./ContentBlockChatOutput";
import type { FinishReason } from "./FinishReason";
import type { RawUsageEntry } from "./RawUsageEntry";
import type { Usage } from "./Usage";

export type ChatInferenceResponse = {
  inference_id: string;
  episode_id: string;
  variant_name: string;
  content: Array<ContentBlockChatOutput>;
  usage: Usage;
  raw_usage?: Array<RawUsageEntry>;
  original_response: string | null;
  finish_reason: FinishReason | null;
};
