// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlockChatOutput } from "./ContentBlockChatOutput";
import type { StoredInput } from "./StoredInput";
import type { ToolCallConfigDatabaseInsert } from "./ToolCallConfigDatabaseInsert";

export type ChatInferenceDatapoint = {
  dataset_name: string;
  function_name: string;
  id: string;
  episode_id: string | null;
  input: StoredInput;
  output?: Array<ContentBlockChatOutput> | null;
  tool_params?: ToolCallConfigDatabaseInsert | null;
  tags?: { [key in string]?: string } | null;
  auxiliary?: string;
  is_deleted: boolean;
  is_custom: boolean;
  source_inference_id?: string | null;
  staled_at?: string | null;
  name?: string | null;
};
