// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlockChatOutput } from "./ContentBlockChatOutput";
import type { StoredInput } from "./StoredInput";
import type { ToolCallConfigDatabaseInsert } from "./ToolCallConfigDatabaseInsert";

export type ChatInferenceDatapointInsert = {
  dataset_name: string;
  function_name: string;
  name?: string;
  id: string;
  episode_id?: string;
  input: StoredInput;
  output?: Array<ContentBlockChatOutput>;
  tool_params?: ToolCallConfigDatabaseInsert;
  tags?: { [key in string]?: string };
  auxiliary: string;
  staled_at?: string;
  source_inference_id?: string;
  is_custom: boolean;
};
