// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlockChatOutput } from "./ContentBlockChatOutput";
import type { StoredInput } from "./StoredInput";
import type { ToolCallConfigDatabaseInsert } from "./ToolCallConfigDatabaseInsert";

export type ChatInferenceDatapoint = {
  dataset_name: string;
  function_name: string;
  id: string;
  episode_id: string | null;
  input: StoredInput;
  output?: Array<ContentBlockChatOutput>;
  tool_params?: ToolCallConfigDatabaseInsert;
  tags?: Record<string, string>;
  auxiliary?: string;
  is_deleted: boolean;
  is_custom: boolean;
  source_inference_id?: string;
  staled_at?: string;
  updated_at: string;
  name?: string;
};
