// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientInputMessageContent } from "./ClientInputMessageContent";
import type { Role } from "./Role";

export type ClientInputMessage = {
  role: Role;
  content: Array<ClientInputMessageContent>;
};
