// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentTargetType } from "./CommentTargetType";

export type CommentFeedbackRow = {
  id: string;
  target_id: string;
  target_type: CommentTargetType;
  value: string;
  tags: { [key in string]?: string };
  timestamp: string;
};
