// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedbackByVariant } from "./FeedbackByVariant";
import type { MetricConfigOptimize } from "./MetricConfigOptimize";

export type ComputeTrackAndStopStateParams = {
  candidate_variants: Array<string>;
  feedback: Array<FeedbackByVariant>;
  min_samples_per_variant: bigint;
  delta: number;
  epsilon: number;
  min_prob?: number;
  metric_optimize: MetricConfigOptimize;
};
