// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionType } from "./FunctionType";

export type CountInferencesForFunctionParams = {
  function_name: string;
  function_type: FunctionType;
};
