// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateDatapointsFromInferenceOutputSource } from "./CreateDatapointsFromInferenceOutputSource";
import type { InferenceFilter } from "./InferenceFilter";

/**
 * Request to create datapoints from inferences.
 */
export type CreateDatapointsFromInferenceRequest = {
  /**
   * When creating the datapoint, this specifies the source of the output for the datapoint.
   * If not provided, by default we will use the original inference output as the datapoint's output
   * (equivalent to `inference`).
   */
  output_source?: CreateDatapointsFromInferenceOutputSource;
} & (
  | {
      type: "inference_ids";
      /**
       * The inference IDs to create datapoints from.
       */
      inference_ids: Array<string>;
    }
  | {
      type: "inference_query";
      /**
       * The function name to filter inferences by.
       */
      function_name: string;
      /**
       * Variant name to filter inferences by, optional.
       */
      variant_name?: string;
      /**
       * Filters to apply when querying inferences, optional.
       */
      filters?: InferenceFilter;
    }
);
