// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of creating a single datapoint from an inference.
 */
export type CreateDatapointResult =
  | {
      status: "success";
      /**
       * The ID of the created datapoint.
       */
      id: string;
      /**
       * The ID of the source inference.
       */
      inference_id: string;
    }
  | {
      status: "error";
      /**
       * The ID of the inference that failed.
       */
      inference_id: string;
      /**
       * The error message.
       */
      error: string;
    };
