// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateDatapointResult } from "./CreateDatapointResult";

/**
 * Response from creating datapoints from inferences.
 */
export type CreateDatapointsFromInferenceResponse = {
  /**
   * Results for each inference, either success with datapoint ID or error.
   */
  datapoints: Array<CreateDatapointResult>;
};
