// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Input } from "./Input";
import type { ProviderTool } from "./ProviderTool";
import type { Tool } from "./Tool";
import type { ToolChoice } from "./ToolChoice";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A request to create a chat datapoint.
 */
export type CreateChatDatapointRequest = {
  /**
   * The function name for this datapoint. Required.
   */
  function_name: string;
  /**
   * Episode ID that the datapoint belongs to. Optional.
   */
  episode_id?: string;
  /**
   * Input to the function. Required.
   */
  input: Input;
  /**
   * Chat datapoint output. Optional.
   * This can be provided as either a string or a list of content blocks.
   * If provided, it will be validated against the function's output schema.
   */
  output?: JsonValue;
  /**
   * Tags associated with this datapoint. Optional.
   */
  tags?: { [key in string]?: string };
  /**
   * Human-readable name for the datapoint. Optional.
   */
  name?: string;
  allowed_tools: Array<string> | null;
  additional_tools: Array<Tool> | null;
  tool_choice: ToolChoice | null;
  parallel_tool_calls: boolean | null;
  provider_tools: Array<ProviderTool> | null;
};
