// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatapointMetadataUpdate } from "./DatapointMetadataUpdate";
import type { Input } from "./Input";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A request to create a JSON datapoint.
 */
export type CreateJsonDatapointRequest = {
  /**
   * The function name for this datapoint. Required.
   */
  function_name: string;
  /**
   * Episode ID that the datapoint belongs to. Optional.
   */
  episode_id?: string;
  /**
   * Input to the function. Required.
   */
  input: Input;
  /**
   * JSON datapoint output. Optional.
   */
  output?: JsonValue;
  /**
   * The output schema of the JSON datapoint. Required.
   */
  output_schema: JsonValue;
  /**
   * Tags associated with this datapoint. Optional.
   */
  tags?: { [key in string]?: string };
  /**
   * Metadata fields. Optional.
   */
  metadata?: DatapointMetadataUpdate;
};
