// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlockChatOutput } from "./ContentBlockChatOutput";
import type { DatapointMetadataUpdate } from "./DatapointMetadataUpdate";
import type { Input } from "./Input";
import type { ToolCallConfigDatabaseInsert } from "./ToolCallConfigDatabaseInsert";

/**
 * A request to create a chat datapoint.
 */
export type CreateChatDatapointRequest = {
  /**
   * The function name for this datapoint. Required.
   */
  function_name: string;
  /**
   * Episode ID that the datapoint belongs to. Optional.
   */
  episode_id?: string;
  /**
   * Input to the function. Required.
   */
  input: Input;
  /**
   * Chat datapoint output. Optional.
   */
  output?: Array<ContentBlockChatOutput>;
  /**
   * Tool parameters for the datapoint. Optional.
   */
  tool_params?: ToolCallConfigDatabaseInsert;
  /**
   * Tags associated with this datapoint. Optional.
   */
  tags?: { [key in string]?: string };
  /**
   * Metadata fields. Optional.
   */
  metadata?: DatapointMetadataUpdate;
};
