// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InferenceFilter } from "./InferenceFilter";

/**
 * Parameters for creating datapoints from inferences.
 * Can specify either a list of inference IDs or a query to find inferences.
 */
export type CreateDatapointsFromInferenceRequestParams =
  | {
      type: "inference_ids";
      /**
       * The inference IDs to create datapoints from.
       */
      inference_ids: Array<string>;
    }
  | {
      type: "inference_query";
      /**
       * The function name to filter inferences by.
       */
      function_name: string;
      /**
       * Variant name to filter inferences by, optional.
       */
      variant_name?: string;
      /**
       * Filters to apply when querying inferences, optional.
       */
      filters?: InferenceFilter;
    };
