// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from creating datapoints (either manually or from inferences).
 */
export type CreateDatapointsResponse = {
  /**
   * The IDs of the newly-generated datapoints.
   */
  ids: Array<string>;
};
