// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Input } from "./Input";
import type { ProviderTool } from "./ProviderTool";
import type { Tool } from "./Tool";
import type { ToolChoice } from "./ToolChoice";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A request to create a chat datapoint.
 */
export type CreateChatDatapointRequest = {
  /**
   * The function name for this datapoint. Required.
   */
  function_name: string;
  /**
   * Episode ID that the datapoint belongs to. Optional.
   */
  episode_id?: string;
  /**
   * Input to the function. Required.
   */
  input: Input;
  /**
   * Chat datapoint output. Optional.
   * This can be provided as either a string or a list of content blocks.
   * If provided, it will be validated against the function's output schema.
   */
  output?: JsonValue;
  /**
   * Tags associated with this datapoint. Optional.
   */
  tags?: { [key in string]?: string };
  /**
   * Human-readable name for the datapoint. Optional.
   */
  name?: string;
  /**
   * A subset of tools configured for the function that the inference is allowed to use. Optional.
   * If not provided, all tools are allowed.
   */
  allowed_tools?: Array<string>;
  /**
   * Tools that the user provided at inference time, in addition to the function-configured tools, that are also allowed.
   * We compile these tools on the fly.
   */
  additional_tools?: Array<Tool>;
  /**
   * User-specified tool choice to force tools or a specific tool to be used in the inference.
   * Optional. If provided during inference, it will override the function-configured tool choice.
   */
  tool_choice?: ToolChoice;
  /**
   * Whether to use parallel tool calls in the inference. Optional.
   * If provided during inference, it will override the function-configured parallel tool calls.
   */
  parallel_tool_calls?: boolean;
  /**
   * Built-in tools that are supported by the model provider.
   */
  provider_tools?: Array<ProviderTool>;
};
