// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialLocation } from "./CredentialLocation";

/**
 * Credential location with optional fallback support
 */
export type CredentialLocationWithFallback =
  | CredentialLocation
  | { default: CredentialLocation; fallback: CredentialLocation };
