// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatInferenceDatapointWire } from "./ChatInferenceDatapointWire";
import type { JsonInferenceDatapoint } from "./JsonInferenceDatapoint";

/**
 * Wire variant of Datapoint enum for API responses with Python/TypeScript bindings
 */
export type DatapointWire =
  | ({ type: "chat" } & ChatInferenceDatapointWire)
  | ({ type: "json" } & JsonInferenceDatapoint);
