// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DatasetMetadata = {
  dataset_name: string;
  count: number;
  last_updated: string;
};
