// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderDirection } from "./OrderDirection";

/**
 * Order by clauses for querying datapoints.
 */
export type DatapointOrderBy = {
  /**
   * The ordering direction.
   */
  direction: OrderDirection;
} & ({ by: "timestamp" } | { by: "search_relevance" });
