// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatInferenceDatapoint } from "./ChatInferenceDatapoint";
import type { JsonInferenceDatapoint } from "./JsonInferenceDatapoint";

/**
 * Wire variant of Datapoint enum for API responses with Python/TypeScript bindings
 * This one should be used in all public interfaces.
 */
export type Datapoint =
  | ({ type: "chat" } & ChatInferenceDatapoint)
  | ({ type: "json" } & JsonInferenceDatapoint);
