// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatInferenceDatapointInsert } from "./ChatInferenceDatapointInsert";
import type { JsonInferenceDatapointInsert } from "./JsonInferenceDatapointInsert";

export type DatapointInsert =
  | ({ type: "chat" } & ChatInferenceDatapointInsert)
  | ({ type: "json" } & JsonInferenceDatapointInsert);
