// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for the delete_datapoints tool (visible to LLM).
 */
export type DeleteDatapointsToolParams = {
  /**
   * The name of the dataset containing the datapoints.
   */
  dataset_name: string;
  /**
   * The IDs of the datapoints to delete.
   */
  ids: Array<string>;
};
