// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filter by whether an inference has demonstration feedback.
 */
export type DemonstrationFeedbackFilter = {
  has_demonstration_feedback: boolean;
};
