// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonMode } from "./JsonMode";
import type { ResolvedTomlPathData } from "./ResolvedTomlPathData";
import type { RetryConfig } from "./RetryConfig";
import type { ServiceTier } from "./ServiceTier";

/**
 * The primary configuration for the Dicl variant
 * We need a helper to deserialize the config because it relies on
 * a path to a file for system instructions and we need to use the
 * load() step to get the fully qualified path.
 */
export type DiclConfig = {
  weight: number | null;
  embedding_model: string;
  k: number;
  model: string;
  system_instructions: ResolvedTomlPathData;
  temperature: number | null;
  top_p: number | null;
  stop_sequences: Array<string> | null;
  presence_penalty: number | null;
  frequency_penalty: number | null;
  max_tokens: number | null;
  seed: number | null;
  json_mode: JsonMode | null;
  retries: RetryConfig;
  max_distance: number | null;
  reasoning_effort?: string;
  service_tier?: ServiceTier;
  thinking_budget_tokens?: number;
  verbosity?: string;
};
