// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RetryConfig } from "./RetryConfig";

export type DiclOptimizationConfig = {
  embedding_model: string;
  variant_name: string;
  function_name: string;
  dimensions: number | null;
  batch_size: number;
  max_concurrency: number;
  retries: RetryConfig;
  k: number;
  model: string;
  credential_location: string | null;
};
