// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiclOptimizationJobHandle = {
  job_url: string;
  embedding_model: string;
  k: number;
  model: string;
};
