// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicJSONSchema } from "./DynamicJSONSchema";

/**
 * Contains the configuration information for a tool defined at runtime
 */
export type DynamicToolConfig = {
  description: string;
  parameters: DynamicJSONSchema;
  name: string;
  strict: boolean;
};
