// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmbeddingProviderConfig } from "./EmbeddingProviderConfig";

export type EmbeddingProviderInfo = {
  inner: EmbeddingProviderConfig;
  timeout_ms: bigint | null;
  provider_name: string;
};
