// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EpisodeByIdRow = {
  episode_id: string;
  count: bigint;
  start_time: string;
  end_time: string;
  last_inference_id: string;
};
