// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a single evaluation run (returned by get_evaluation_run_infos).
 */
export type EvaluationRunInfoById = {
  evaluation_run_id: string;
  variant_name: string;
  most_recent_inference_date: string;
};
