// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EvaluationRunStartEvent = {
  evaluation_run_id: string;
  num_datapoints: number;
  evaluation_name: string;
  dataset_name: string | null;
  variant_name: string;
};
