// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExactMatchConfig } from "./ExactMatchConfig";
import type { LLMJudgeConfig } from "./LLMJudgeConfig";
import type { ToolUseConfig } from "./ToolUseConfig";

export type EvaluatorConfig =
  | ({ type: "exact_match" } & ExactMatchConfig)
  | ({ type: "llm_judge" } & LLMJudgeConfig)
  | ({ type: "tool_use" } & ToolUseConfig);
