// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputMessage } from "./InputMessage";
import type { StatusUpdate } from "./StatusUpdate";

/**
 * The payload of an event.
 */
export type EventPayload =
  | ({ type: "message" } & InputMessage)
  | { type: "status_update"; status_update: StatusUpdate };
