// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputMessage } from "./InputMessage";
import type { StatusUpdate } from "./StatusUpdate";
import type { ToolCall } from "./ToolCall";
import type { ToolCallAuthorization } from "./ToolCallAuthorization";
import type { ToolOutcome } from "./ToolOutcome";

/**
 * The payload of an event.
 */
export type EventPayload =
  | ({ type: "message" } & InputMessage)
  | { type: "status_update"; status_update: StatusUpdate }
  | ({ type: "tool_call" } & ToolCall)
  | ({ type: "tool_call_authorization" } & ToolCallAuthorization)
  | { type: "tool_result"; tool_call_event_id: string; outcome: ToolOutcome }
  | { type: "other" };
