// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserQuestionAnswer } from "./UserQuestionAnswer";

/**
 * User responses payload for an event.
 */
export type EventPayloadUserQuestionsAnswers = {
  /**
   * Map from question UUID to response.
   */
  responses: { [key in string]: UserQuestionAnswer };
  user_questions_event_id: string;
};
