// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VisualizationType } from "./VisualizationType";

/**
 * Visualization payload for an event.
 */
export type EventPayloadVisualization = {
  /**
   * The tool call event ID that generated this visualization.
   */
  tool_call_event_id: string;
  /**
   * The visualization data.
   */
  visualization: VisualizationType;
};
