// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatusUpdate } from "./StatusUpdate";

/**
 * Status update payload for an event.
 */
export type EventPayloadStatusUpdate = { status_update: StatusUpdate };
