// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StaticWeightsConfig } from "./StaticWeightsConfig";
import type { TrackAndStopConfig } from "./TrackAndStopConfig";
import type { UniformConfig } from "./UniformConfig";

export type ExperimentationConfig =
  | ({ type: "uniform" } & UniformConfig)
  | ({ type: "static_weights" } & StaticWeightsConfig)
  | ({ type: "track_and_stop" } & TrackAndStopConfig);
