// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtraHeader =
  | {
      /**
       * A fully-qualified model provider name in your configuration (e.g. `tensorzero::model_name::my_model::provider_name::my_provider`)
       */
      model_provider_name: string;
      /**
       * The name of the HTTP header (e.g. `anthropic-beta`)
       */
      name: string;
      /**
       * The value of the HTTP header (e.g. `feature1,feature2,feature3`)
       */
      value: string;
    }
  | {
      /**
       * A fully-qualified model provider name in your configuration (e.g. `tensorzero::model_name::my_model::provider_name::my_provider`)
       */
      model_provider_name: string;
      /**
       * The name of the HTTP header (e.g. `anthropic-beta`)
       */
      name: string;
      /**
       * Set to true to remove the header from the model provider request
       */
      delete: null;
    }
  | {
      /**
       * A variant name in your configuration (e.g. `my_variant`)
       */
      variant_name: string;
      /**
       * The name of the HTTP header (e.g. `anthropic-beta`)
       */
      name: string;
      /**
       * The value of the HTTP header (e.g. `feature1,feature2,feature3`)
       */
      value: string;
    }
  | {
      /**
       * A variant name in your configuration (e.g. `my_variant`)
       */
      variant_name: string;
      /**
       * The name of the HTTP header (e.g. `anthropic-beta`)
       */
      name: string;
      /**
       * Set to true to remove the header from the model provider request
       */
      delete: null;
    }
  | {
      /**
       * A model name in your configuration (e.g. `my_gpt_5`) or a short-hand model name (e.g. `openai::gpt-5`)
       */
      model_name: string;
      /**
       * A provider name for the model you specified (e.g. `my_openai`).
       */
      provider_name: string | null;
      /**
       * The name of the HTTP header (e.g. `anthropic-beta`)
       */
      name: string;
      /**
       * The value of the HTTP header (e.g. `feature1,feature2,feature3`)
       */
      value: string;
    }
  | {
      /**
       * A model name in your configuration (e.g. `my_gpt_5`) or a short-hand model name (e.g. `openai::gpt-5`)
       */
      model_name: string;
      /**
       * A provider name for the model you specified (e.g. `my_openai`)
       */
      provider_name: string | null;
      /**
       * The name of the HTTP header (e.g. `anthropic-beta`)
       */
      name: string;
      /**
       * Set to true to remove the header from the model provider request
       */
      delete: null;
    }
  | {
      /**
       * The name of the HTTP header (e.g. `anthropic-beta`)
       */
      name: string;
      /**
       * The value of the HTTP header (e.g. `feature1,feature2,feature3`)
       */
      value: string;
    }
  | {
      /**
       * The name of the HTTP header (e.g. `anthropic-beta`)
       */
      name: string;
      /**
       * Set to true to remove the header from the model provider request
       */
      delete: null;
    };
