// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedbackBoundsByType } from "./FeedbackBoundsByType";

export type FeedbackBounds = {
  first_id: string | null;
  last_id: string | null;
  by_type: FeedbackBoundsByType;
};
