// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Base64FileMetadata } from "./Base64FileMetadata";
import type { StoragePath } from "./StoragePath";

/**
 * A file for an inference or a datapoint.
 */
export type File =
  | { url: string; mime_type: string | null }
  | { mime_type: string; data: string }
  | { metadata: Base64FileMetadata; storage_path: StoragePath };
