// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type File =
  | { url: string; mime_type?: string }
  | { mime_type: string; data: string };
