// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Base64File } from "./Base64File";
import type { ObjectStorageFile } from "./ObjectStorageFile";
import type { ResolvedObjectStorageFile } from "./ResolvedObjectStorageFile";
import type { UrlFile } from "./UrlFile";

/**
 * A file for an inference or a datapoint.
 */
export type File =
  | ({ file_type: "url" } & UrlFile)
  | ({ file_type: "base64" } & Base64File)
  | ({ file_type: "object_storage" } & ObjectStorageFile)
  | ({ file_type: "resolved_object_storage" } & ResolvedObjectStorageFile);
