// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatapointKind } from "./DatapointKind";
import type { DatasetOutputSource } from "./DatasetOutputSource";
import type { MetricFilter } from "./MetricFilter";

/**
 * Request body for counting and inserting matching inferences into a dataset
 */
export type FilterInferencesForDatasetBuilderRequest = {
  /**
   * The type of inference to filter for (chat or json)
   */
  inference_type: DatapointKind;
  /**
   * Optional function name to filter by
   */
  function_name?: string;
  /**
   * Optional variant name to filter by (requires function_name)
   */
  variant_name?: string;
  /**
   * How to handle the output field when matching
   */
  output_source: DatasetOutputSource;
  /**
   * Optional metric filter to apply
   */
  metric_filter?: MetricFilter;
};
