// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InferenceExtraHeader } from "./InferenceExtraHeader";

/**
 * The result of filtering `InferenceExtraHeader` by variant name.
 */
export type FilteredInferenceExtraHeaders = {
  data: Array<InferenceExtraHeader>;
};
