// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Minimal job handle for Fireworks SFT.
 * All configuration needed for polling comes from provider_types at poll time.
 */
export type FireworksSFTJobHandle = { job_url: string; job_path: string };
