// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FireworksSFTJobHandle = {
  api_base: string;
  account_id: string;
  job_url: string;
  job_path: string;
  deploy_after_training: boolean;
  credential_location: string | null;
};
