// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Row returned from the list_functions_with_inference_count query.
 */
export type FunctionInferenceCount = {
  function_name: string;
  /**
   * ISO 8601 timestamp of the most recent inference for this function
   */
  last_inference_timestamp: string;
  /**
   * Total number of inferences for this function
   */
  inference_count: number;
};
