// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GatewayToolCallAuthorizationStatus } from "./GatewayToolCallAuthorizationStatus";
import type { ToolCallDecisionSource } from "./ToolCallDecisionSource";

/**
 * Tool call authorization payload as seen by gateway consumers.
 *
 * Uses `GatewayToolCallAuthorizationStatus` which excludes `NotAvailable`.
 */
export type GatewayEventPayloadToolCallAuthorization = {
  source: ToolCallDecisionSource;
  tool_call_event_id: string;
  status: GatewayToolCallAuthorizationStatus;
};
