// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventPayloadError } from "./EventPayloadError";
import type { EventPayloadMessage } from "./EventPayloadMessage";
import type { EventPayloadStatusUpdate } from "./EventPayloadStatusUpdate";
import type { EventPayloadToolCall } from "./EventPayloadToolCall";
import type { EventPayloadToolResult } from "./EventPayloadToolResult";
import type { GatewayEventPayloadToolCallAuthorization } from "./GatewayEventPayloadToolCallAuthorization";

/**
 * Event payload as seen by gateway consumers.
 *
 * Uses `GatewayEventPayloadToolCallAuthorization` which excludes `NotAvailable` status.
 */
export type GatewayEventPayload =
  | ({ type: "message" } & EventPayloadMessage)
  | ({ type: "error" } & EventPayloadError)
  | ({ type: "status_update" } & EventPayloadStatusUpdate)
  | ({ type: "tool_call" } & EventPayloadToolCall)
  | ({
      type: "tool_call_authorization";
    } & GatewayEventPayloadToolCallAuthorization)
  | ({ type: "tool_result" } & EventPayloadToolResult)
  | { type: "unknown" };
