// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportConfig } from "./ExportConfig";
import type { ObservabilityConfig } from "./ObservabilityConfig";
import type { TemplateFilesystemAccess } from "./TemplateFilesystemAccess";

export type GatewayConfig = {
  bind_address: string | null;
  observability: ObservabilityConfig;
  debug: boolean;
  template_filesystem_access: TemplateFilesystemAccess;
  export: ExportConfig;
  base_path: string | null;
  /**
   * If enabled, adds an 'error_json' field alongside the human-readable 'error' field
   * in HTTP error responses. This contains a JSON-serialized version of the error.
   * While 'error_json' will always be valid JSON when present, the exact contents is unstable,
   * and may change at any time without warning.
   * For now, this is only supported in the standalone gateway, and not in the embedded gateway.
   */
  unstable_error_json: boolean;
};
