// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GatewayEvent } from "./GatewayEvent";

/**
 * Response from listing workspace pending tool calls as seen by gateway consumers.
 *
 * Uses `GatewayEvent` which excludes `NotAvailable` authorization status.
 */
export type GatewayWorkspacePendingToolCallsResponse = {
  pending_tool_calls: Array<GatewayEvent>;
  /**
   * If there are no events in the workspace yet this should return None
   */
  last_event_id: string | null;
};
