// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GCPBatchConfigCloudStorage } from "./GCPBatchConfigCloudStorage";

export type GCPBatchConfigType =
  | { storage_type: "none" }
  | ({ storage_type: "cloud_storage" } & GCPBatchConfigCloudStorage);
