// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Minimal job handle for GCP Vertex Gemini SFT.
 * All configuration needed for polling comes from provider_types at poll time.
 */
export type GCPVertexGeminiSFTJobHandle = {
  job_url: string;
  /**
   * The API resource name (e.g., projects/{project}/locations/{region}/tuningJobs/{job_id})
   */
  job_name: string;
};
