// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GCPBatchConfigType } from "./GCPBatchConfigType";
import type { GCPDefaults } from "./GCPDefaults";
import type { GCPSFTConfig } from "./GCPSFTConfig";

export type GCPVertexGeminiProviderTypeConfig = {
  batch?: GCPBatchConfigType;
  sft?: GCPSFTConfig;
  defaults: GCPDefaults;
};
