// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GCPVertexGeminiSFTConfig = {
  model: string;
  bucket_name: string;
  project_id: string;
  region: string;
  learning_rate_multiplier?: number;
  adapter_size?: number;
  n_epochs?: number;
  export_last_checkpoint_only?: boolean;
  credential_location: string | null;
  seed?: bigint;
  api_base?: string;
  service_account?: string;
  kms_key_name?: string;
  tuned_model_display_name?: string;
  bucket_path_prefix?: string;
};
