// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type GCPVertexAnthropicProvider = {
  model_id: string;
  request_url: string;
  streaming_request_url: string;
  audience: string;
  provider_tools: Array<JsonValue>;
};
