// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GCPVertexAnthropicProvider = {
  model_id: string;
  request_url: string;
  streaming_request_url: string;
  audience: string;
};
