// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionDatapointCount } from "./FunctionDatapointCount";

/**
 * Response containing datapoint counts grouped by function
 */
export type GetDatapointCountsByFunctionResponse = {
  /**
   * The counts of datapoints per function, ordered by count DESC
   */
  counts: Array<FunctionDatapointCount>;
};
