// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetDatasetMetadataParams = {
  /**
   * Only select datasets matching a specific function.
   */
  function_name?: string;
  /**
   * The maximum number of datasets to return.
   */
  limit?: number;
  /**
   * The number of datasets to skip before starting to return results.
   */
  offset?: number;
};
