// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatapointWire } from "./DatapointWire";

/**
 * Response containing the requested datapoints.
 */
export type GetDatapointsResponse = {
  /**
   * The retrieved datapoints.
   */
  datapoints: Array<DatapointWire>;
};
