// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetFeedbackTimeseriesParams = {
  function_name: string;
  metric_name: string;
  variant_names?: Array<string>;
  interval_minutes: number;
  max_periods: number;
};
