// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InferenceOutputSource } from "./InferenceOutputSource";

/**
 * Parameters for the get_inferences tool (visible to LLM).
 */
export type GetInferencesToolParams = {
  /**
   * The IDs of the inferences to retrieve. Required.
   */
  ids: Array<string>;
  /**
   * Optional function name to filter by.
   * Including this improves query performance since `function_name` is the first column
   * in the ClickHouse primary key.
   */
  function_name?: string;
  /**
   * Source of the inference output.
   * Determines whether to return the original inference output or demonstration feedback
   * (manually-curated output) if available.
   * Defaults to `Inference` if not specified.
   */
  output_source: InferenceOutputSource;
};
