// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to get specific inferences by their IDs.
 * Used by the `POST /v1/inferences/get_inferences` endpoint.
 */
export type GetInferencesRequest = {
  /**
   * The IDs of the inferences to retrieve. Required.
   */
  ids: Array<string>;
};
