// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response containing the inference table bounds.
 * Used by the `GET /internal/inferences/bounds` endpoint.
 */
export type GetInferenceBoundsResponse = {
  /**
   * The most recent inference ID (MAX id_uint).
   */
  latest_id?: string;
  /**
   * The oldest inference ID (MIN id_uint).
   */
  earliest_id?: string;
  /**
   * The total number of inferences matching the filter criteria.
   */
  count: bigint;
};
