// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoredInference } from "./StoredInference";

/**
 * Response containing the requested inferences.
 */
export type GetInferencesResponse = {
  /**
   * The retrieved inferences.
   */
  inferences: Array<StoredInference>;
};
