// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelUsageTimePoint } from "./ModelUsageTimePoint";

/**
 * Response containing model usage timeseries data.
 */
export type GetModelUsageResponse = {
  /**
   * The model usage data points.
   */
  data: Array<ModelUsageTimePoint>;
};
