// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelLatencyDatapoint } from "./ModelLatencyDatapoint";

/**
 * Response containing model latency quantile data.
 */
export type GetModelLatencyResponse = {
  /**
   * The model latency data points with quantile distributions.
   */
  data: Array<ModelLatencyDatapoint>;
};
