// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StaticJSONSchema } from "./StaticJSONSchema";

/**
 * Contains the configuration information for a tool used in implicit tool calling for
 * JSON schema enforcement
 */
export type ImplicitToolConfig = { parameters: StaticJSONSchema };
