// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InferenceExtraHeader =
  | ({ model_provider_name: string; name: string } & (
      | { value: string }
      | "delete"
    ))
  | ({ variant_name: string; name: string } & ({ value: string } | "delete"))
  | ({ name: string } & ({ value: string } | "delete"));
