// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BooleanMetricFilter } from "./BooleanMetricFilter";
import type { FloatMetricFilter } from "./FloatMetricFilter";
import type { TagFilter } from "./TagFilter";
import type { TimeFilter } from "./TimeFilter";

/**
 * Filters for querying inferences.
 */
export type InferenceFilter =
  | ({ type: "float_metric" } & FloatMetricFilter)
  | ({ type: "boolean_metric" } & BooleanMetricFilter)
  | ({ type: "tag" } & TagFilter)
  | ({ type: "time" } & TimeFilter)
  | { type: "and"; children: Array<InferenceFilter> }
  | { type: "or"; children: Array<InferenceFilter> }
  | { type: "not"; child: InferenceFilter };
