// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Grouping options for inference statistics
 */
export type InferenceStatsGroupBy = "variant";
