// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type InferenceExtraBody =
  | ({ model_provider_name: string; pointer: string } & (
      | { value: JsonValue }
      | "delete"
    ))
  | ({ variant_name: string; pointer: string } & (
      | { value: JsonValue }
      | "delete"
    ));
