// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InferenceExtraBodyProviderType =
  | { model_provider_name: string }
  | { variant_name: string }
  | { model_name: string; provider_name?: string }
  | { always: boolean };
