// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { File } from "./File";
import type { RawText } from "./RawText";
import type { Template } from "./Template";
import type { Text } from "./Text";
import type { Thought } from "./Thought";
import type { ToolCallWrapper } from "./ToolCallWrapper";
import type { ToolResult } from "./ToolResult";
import type { Unknown } from "./Unknown";

export type InputMessageContent =
  | ({ type: "text" } & Text)
  | ({ type: "template" } & Template)
  | ({ type: "tool_call" } & ToolCallWrapper)
  | ({ type: "tool_result" } & ToolResult)
  | ({ type: "raw_text" } & RawText)
  | ({ type: "thought" } & Thought)
  | ({ type: "file" } & File)
  | ({ type: "unknown" } & Unknown);
