// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputMessage } from "./InputMessage";
import type { System } from "./System";

/**
 * API representation of an input to a model.
 */
export type Input = {
  /**
   * System prompt of the input.
   */
  system?: System;
  /**
   * Messages in the input.
   */
  messages: Array<InputMessage>;
};
