// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputMessageContent } from "./InputMessageContent";
import type { Role } from "./Role";

/**
 * An input message in a conversation.
 */
export type InputMessage = { role: Role; content: Array<InputMessageContent> };
