// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata about an inference.
 * Used by the `GET /internal/inferences` endpoint.
 */
export type InternalInferenceMetadata = {
  /**
   * The ID of the inference.
   */
  id: string;
  /**
   * The function name of the inference.
   */
  function_name: string;
  /**
   * The variant name of the inference.
   */
  variant_name: string;
  /**
   * The episode ID of the inference.
   */
  episode_id: string;
  /**
   * The function type of the inference.
   */
  function_type: string;
  /**
   * The timestamp of the inference.
   */
  timestamp: string;
};
