// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InternalInferenceMetadata } from "./InternalInferenceMetadata";

/**
 * Response containing the list of inferences by ID.
 */
export type InternalListInferencesByIdResponse = {
  /**
   * The list of inferences.
   */
  inferences: Array<InternalInferenceMetadata>;
};
