// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonInferenceOutput } from "./JsonInferenceOutput";
import type { StoredInput } from "./StoredInput";

/**
 * Evaluation result for a JSON function.
 */
export type JsonEvaluationResultRow = {
  inference_id: string;
  episode_id: string;
  datapoint_id: string;
  evaluation_run_id: string;
  /**
   * The evaluator inference ID, if the feedback was generated by an LLM judge
   */
  evaluator_inference_id?: string;
  /**
   * The input to the function
   */
  input: StoredInput;
  /**
   * The generated output from the model
   */
  generated_output: JsonInferenceOutput;
  /**
   * The reference output from the datapoint
   */
  reference_output?: JsonInferenceOutput;
  dataset_name: string;
  /**
   * The name of the metric (e.g., "tensorzero::evaluation_name::haiku::evaluator_name::exact_match")
   */
  metric_name?: string;
  /**
   * The metric value as a string (could be boolean or float)
   */
  metric_value?: string;
  /**
   * The feedback ID for this metric
   */
  feedback_id?: string;
  /**
   * Whether this feedback was human-submitted
   */
  is_human_feedback: boolean;
  /**
   * The variant name used for this inference
   */
  variant_name: string;
  /**
   * The datapoint name (if any)
   */
  name?: string;
  /**
   * When the datapoint was marked as stale (if ever)
   */
  staled_at?: string;
};
