// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JsonInferenceDatapointInsert = {
  dataset_name?: string;
  function_name: string;
  name?: string;
  id: string;
  episode_id?: string;
  input: string;
  output?: string;
  output_schema: string;
  tags: { [key in string]?: string };
  auxiliary: string;
  staled_at?: string;
  source_inference_id?: string;
  is_custom: boolean;
};
