// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinishReason } from "./FinishReason";
import type { JsonInferenceOutput } from "./JsonInferenceOutput";
import type { Usage } from "./Usage";

export type JsonInferenceResponse = {
  inference_id: string;
  episode_id: string;
  variant_name: string;
  output: JsonInferenceOutput;
  usage: Usage;
  original_response: string | null;
  finish_reason: FinishReason | null;
};
