// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeyInfo = {
  public_id: string;
  organization: string;
  workspace: string;
  description?: string;
  created_at: string;
  disabled_at?: string;
};
