// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClickhouseFormat } from "./ClickhouseFormat";
import type { OptimizationData } from "./OptimizationData";
import type { UninitializedOptimizerInfo } from "./UninitializedOptimizerInfo";

/**
 * Parameters for launch_optimization_workflow
 */
export type LaunchOptimizationWorkflowParams = {
  render_variant_name: string;
  data: OptimizationData;
  val_fraction: number | null;
  format: ClickhouseFormat;
  optimizer_config: UninitializedOptimizerInfo;
};
