// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RenderedSample } from "./RenderedSample";
import type { UninitializedOptimizerInfo } from "./UninitializedOptimizerInfo";

export type LaunchOptimizationParams = {
  train_examples: Array<RenderedSample>;
  val_examples: Array<RenderedSample> | null;
  optimizer_config: UninitializedOptimizerInfo;
};
