// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Legacy `type = "uniform"` config. Converts to `StaticExperimentationConfig` with equal weights.
 */
export type LegacyUniformExperimentationConfig = {
  candidate_variants?: Array<string>;
  fallback_variants?: Array<string>;
};
