// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GetInferencesResponse } from "./GetInferencesResponse";

/**
 * Response for the list_inferences endpoint.
 * Can return either full inference objects or just IDs depending on the request's `response_format`.
 */
export type ListInferencesResponse =
  | GetInferencesResponse
  | {
      /**
       * The inference IDs.
       */
      ids: Array<string>;
    };
