// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "./Event";

/**
 * Response from listing config writes.
 */
export type ListConfigWritesResponse = { config_writes: Array<Event> };
