// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InferenceMetadata } from "./InferenceMetadata";

/**
 * Response containing a list of inference metadata
 */
export type ListInferenceMetadataResponse = {
  inference_metadata: Array<InferenceMetadata>;
};
