// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoredInference } from "./StoredInference";

/**
 * Response containing a list of inferences for an episode
 */
export type ListEpisodeInferencesResponse = {
  inferences: Array<StoredInference>;
};
