// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InferenceFilter } from "./InferenceFilter";
import type { InferenceOutputSource } from "./InferenceOutputSource";
import type { OrderBy } from "./OrderBy";

/**
 * Request to list inferences with pagination and filters.
 * Used by the `POST /v1/inferences/list_inferences` endpoint.
 */
export type ListInferencesRequest = {
  /**
   * Optional function name to filter inferences by.
   * If provided, only inferences from this function will be returned.
   */
  function_name: string | null;
  /**
   * Optional variant name to filter inferences by.
   * If provided, only inferences from this variant will be returned.
   */
  variant_name: string | null;
  /**
   * Optional episode ID to filter inferences by.
   * If provided, only inferences from this episode will be returned.
   */
  episode_id: string | null;
  /**
   * Source of the inference output. Determines whether to return the original
   * inference output or demonstration feedback (manually-curated output) if available.
   */
  output_source: InferenceOutputSource;
  /**
   * The maximum number of inferences to return.
   * Defaults to 20.
   */
  page_size: number | null;
  /**
   * The number of inferences to skip before starting to return results.
   * Defaults to 0.
   */
  offset: number | null;
  /**
   * Optional filter to apply when querying inferences.
   * Supports filtering by metrics, tags, time, and logical combinations (AND/OR/NOT).
   */
  filter: InferenceFilter | null;
  /**
   * Optional ordering criteria for the results.
   * Supports multiple sort criteria (e.g., sort by timestamp then by metric).
   */
  order_by: Array<OrderBy> | null;
};
