// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatapointFilter } from "./DatapointFilter";

/**
 * Request to list datapoints from a dataset with pagination and filters.
 * Used by the `POST /v1/datasets/{dataset_id}/list_datapoints` endpoint.
 */
export type ListDatapointsRequest = {
  /**
   * Optional function name to filter datapoints by.
   * If provided, only datapoints from this function will be returned.
   */
  function_name: string | null;
  /**
   * The maximum number of datapoints to return.
   * Defaults to 20.
   */
  page_size: number | null;
  /**
   * The number of datapoints to skip before starting to return results.
   * Defaults to 0.
   */
  offset: number | null;
  /**
   * Optional filter to apply when querying datapoints.
   * Supports filtering by tags, time, and logical combinations (AND/OR/NOT).
   */
  filter: DatapointFilter | null;
};
