// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GetDatapointsResponse } from "./GetDatapointsResponse";
import type { ListDatapointsIdsOnlyResponse } from "./ListDatapointsIdsOnlyResponse";

/**
 * Response from the `list_datapoints` endpoint.
 * The structure depends on the `response_format` parameter in the request.
 */
export type ListDatapointsResponse =
  | GetDatapointsResponse
  | ListDatapointsIdsOnlyResponse;
