// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query parameters for listing config writes.
 */
export type ListConfigWritesParams = {
  /**
   * Maximum number of config writes to return. Defaults to 20.
   */
  limit?: number;
  /**
   * Offset for pagination.
   */
  offset?: number;
};
