// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query parameters for listing events.
 */
export type ListEventsParams = {
  /**
   * Maximum number of events to return. Defaults to 20.
   */
  limit?: number;
  /**
   * Cursor for pagination: return events with id < before.
   */
  before?: string;
};
