// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VariantStats } from "./VariantStats";

/**
 * Response containing all variants for a function with their statistics
 */
export type ListVariantsResponse = {
  /**
   * List of all configured variants with their usage statistics
   */
  variants: Array<VariantStats>;
};
