// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatasetMetadata } from "./DatasetMetadata";

/**
 * Response containing a list of datasets.
 */
export type ListDatasetsResponse = {
  /**
   * List of dataset metadata.
   */
  datasets: Array<DatasetMetadata>;
};
