// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MetricsConfig = {
  /**
   * Histogram buckets for the `tensorzero_inference_latency_overhead_seconds` metric.
   * Defaults to `[0.001, 0.01, 0.1]`. Set to empty to disable the metric.
   */
  tensorzero_inference_latency_overhead_seconds_buckets?: Array<number>;
};
