// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricType } from "./MetricType";

export type MetricWithFeedback = {
  function_name: string;
  metric_name: string;
  /**
   * The type of metric (boolean, float, demonstration).
   * None if the metric is not in the current config (e.g., was deleted).
   */
  metric_type?: MetricType;
  feedback_count: number;
};
