// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelInferenceRow = {
  id: string;
  inference_id: string;
  raw_request: string;
  raw_response: string;
  model_name: string;
  model_provider_name: string;
  input_tokens: bigint | null;
  output_tokens: bigint | null;
  response_time_ms: bigint;
  ttft_ms: bigint | null;
  timestamp: string;
  system: string | null;
  input_messages: string;
  output: string;
  cached: boolean;
  extra_body: string | null;
  tags: { [key in string]?: string };
};
