// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelLatencyDatapoint = {
  model_name: string;
  response_time_ms_quantiles: Array<number | null>;
  ttft_ms_quantiles: Array<number | null>;
  count: bigint;
};
