// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelUsageTimePoint = {
  period_start: string;
  model_name: string;
  input_tokens: bigint;
  output_tokens: bigint;
  count: bigint;
};
