// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user's answer to a multiple choice question.
 */
export type MultipleChoiceAnswer = {
  /**
   * IDs of the selected options.
   */
  selected: Array<string>;
};
