// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Round-robin sampler for variants in the cold-start phase.
 *
 * The nursery holds variants that don't yet have enough data for statistical
 * analysis (i.e., fewer than `min_samples_per_variant` samples). It uses an
 * atomic counter to implement thread-safe round-robin sampling, ensuring each
 * variant gets sampled until it graduates to the bandit phase.
 *
 * When serialized for external use, only the variant list is exposed (not the atomic counter).
 */
export type Nursery = { variants: Array<string> };
