// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoragePath } from "./StoragePath";

/**
 * A file that we failed to read from object storage.
 * This struct can NOT be stored in the database.
 */
export type ObjectStorageError = {
  error: string | null;
  source_url?: string;
  mime_type: string;
  storage_path: StoragePath;
};
