// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchWritesConfig } from "./BatchWritesConfig";

export type ObservabilityConfig = {
  enabled: boolean | null;
  async_writes: boolean;
  batch_writes: BatchWritesConfig;
  disable_automatic_migrations: boolean;
};
