// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenAICustomToolFormat } from "./OpenAICustomToolFormat";

/**
 * `OpenAICustomTool` represents OpenAI's custom tool format, which allows
 * for text or grammar-based tool definitions beyond standard function calling.
 */
export type OpenAICustomTool = {
  name: string;
  description: string | null;
  format: OpenAICustomToolFormat | null;
};
