// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OpenAISFTConfig = {
  model: string;
  batch_size?: number;
  learning_rate_multiplier?: number;
  n_epochs?: number;
  credential_location: string | null;
  seed?: bigint;
  suffix?: string;
  api_base?: string;
};
