// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OpenAISimilarityMetric =
  | "fuzzy_match"
  | "bleu"
  | "gleu"
  | "meteor"
  | "rouge1"
  | "rouge2"
  | "rouge3"
  | "rouge4"
  | "rouge5"
  | "rouge_l";
