// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenAIModelGraderInput } from "./OpenAIModelGraderInput";
import type { OpenAISimilarityMetric } from "./OpenAISimilarityMetric";
import type { OpenAIStringCheckOp } from "./OpenAIStringCheckOp";
import type { TomlRelativePath } from "./TomlRelativePath";

export type OpenAIGrader =
  | {
      type: "string_check";
      name: string;
      operation: OpenAIStringCheckOp;
      input: TomlRelativePath;
      reference: TomlRelativePath;
    }
  | {
      type: "text_similarity";
      name: string;
      evaluation_metric: OpenAISimilarityMetric;
      input: TomlRelativePath;
      reference: TomlRelativePath;
    }
  | {
      type: "score_model";
      name: string;
      model: string;
      input: Array<OpenAIModelGraderInput>;
      range: [number, number] | null;
    }
  | {
      type: "label_model";
      name: string;
      model: string;
      labels: Array<string>;
      passing_labels: Array<string>;
      input: Array<OpenAIModelGraderInput>;
    }
  | {
      type: "python";
      name: string;
      source: TomlRelativePath;
      image_tag: string | null;
    }
  | {
      type: "multi";
      calculate_output: string;
      graders: { [key in string]?: OpenAIGrader };
      name: string;
    };
