// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FireworksSFTJobHandle } from "./FireworksSFTJobHandle";
import type { OpenAISFTJobHandle } from "./OpenAISFTJobHandle";
import type { TogetherSFTJobHandle } from "./TogetherSFTJobHandle";

export type OptimizationJobHandle =
  | ({ type: "openai_sft" } & OpenAISFTJobHandle)
  | ({ type: "fireworks_sft" } & FireworksSFTJobHandle)
  | ({ type: "together_sft" } & TogetherSFTJobHandle);
