// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptimizerOutput } from "./OptimizerOutput";
import type { JsonValue } from "./serde_json/JsonValue";

export type OptimizationJobInfo =
  | {
      status: "pending";
      message: string;
      estimated_finish: Date | null;
      trained_tokens: bigint | null;
      error: JsonValue | null;
    }
  | { status: "completed"; output: OptimizerOutput }
  | { status: "failed"; message: string; error: JsonValue | null };
