// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ListDatapointsData } from "./ListDatapointsData";
import type { ListInferencesParams } from "./ListInferencesParams";

/**
 * Data source for launch_optimization_workflow
 */
export type OptimizationData =
  | ({ type: "experimental_list_inferences" } & ListInferencesParams)
  | ({ type: "list_datapoints" } & ListDatapointsData);
