// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FireworksSFTConfig } from "./FireworksSFTConfig";
import type { GCPVertexGeminiSFTConfig } from "./GCPVertexGeminiSFTConfig";
import type { OpenAIRFTConfig } from "./OpenAIRFTConfig";
import type { OpenAISFTConfig } from "./OpenAISFTConfig";
import type { TogetherSFTConfig } from "./TogetherSFTConfig";

export type OptimizerConfig =
  | { OpenAISFT: OpenAISFTConfig }
  | { OpenAIRFT: OpenAIRFTConfig }
  | { FireworksSFT: FireworksSFTConfig }
  | { GCPVertexGeminiSFT: GCPVertexGeminiSFTConfig }
  | { TogetherSFT: TogetherSFTConfig };
