// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OtlpTracesFormat } from "./OtlpTracesFormat";

<<<<<<< HEAD
export type OtlpTracesConfig = { 
/**
 * Enable OpenTelemetry traces export to the configured OTLP endpoint (configured via OTLP environment variables)
 */
enabled: boolean, };
=======
export type OtlpTracesConfig = {
  /**
   * Enable OpenTelemetry traces export to the configured OTLP endpoint (configured via OTLP environment variables)
   */
  enabled: boolean;
  format: OtlpTracesFormat;
};
>>>>>>> upstream/main
