// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderToolScope = null | {
  model_name: string;
  model_provider_name: string;
};
