// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QueryDemonstrationFeedbackByInferenceIdParams = {
  inference_id: string;
  before: string | null;
  after: string | null;
  page_size: number | null;
};
