// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateLimit } from "./RateLimit";
import type { RateLimitingConfigScope } from "./RateLimitingConfigScope";

export type RateLimitingConfigRule = {
  limits: Array<RateLimit>;
  scope: Array<RateLimitingConfigScope>;
} & ({ Priority: number } | "Always");
