// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateLimitingConfigScope } from "./RateLimitingConfigScope";

/**
 * Wrapper type for rate limiting scopes.
 * Forces them to be sorted on construction
 */
export type RateLimitingConfigScopes = Array<RateLimitingConfigScope>;
