// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Location for AWS region configuration, supporting static values, environment variables, or dynamic resolution.
 */
export type RegionLocation =
  | { Env: string }
  | { Dynamic: string }
  | { Static: string };
