// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlockChatOutput } from "./ContentBlockChatOutput";
import type { DynamicToolParams } from "./DynamicToolParams";
import type { ModelInput } from "./ModelInput";
import type { StoredInput } from "./StoredInput";
import type { StoredOutput } from "./StoredOutput";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Represents an inference that has been prepared for fine-tuning.
 * This is constructed by rendering a StoredInference with a variant for messages
 * and by resolving all network resources (e.g. images).
 * This is a wire type - it uses DynamicToolParams and has Python/TypeScript bindings.
 */
export type RenderedSample = {
  function_name: string;
  input: ModelInput;
  stored_input: StoredInput;
  output: Array<ContentBlockChatOutput> | null;
  stored_output: StoredOutput | null;
  dispreferred_outputs: Array<Array<ContentBlockChatOutput>>;
  episode_id: string | null;
  inference_id: string | null;
  tool_params: DynamicToolParams;
  output_schema: JsonValue | null;
  tags: { [key in string]?: string };
};
