// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlockChatOutput } from "./ContentBlockChatOutput";
import type { FunctionTool } from "./FunctionTool";
import type { ModelInput } from "./ModelInput";
import type { ProviderTool } from "./ProviderTool";
import type { StoredInput } from "./StoredInput";
import type { StoredOutput } from "./StoredOutput";
import type { ToolChoice } from "./ToolChoice";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Represents an inference that has been prepared for fine-tuning.
 * This is constructed by rendering a StoredInference with a variant for messages
 * and by resolving all network resources (e.g. images).
 * This is a wire type - it uses DynamicToolParams and has Python/TypeScript bindings.
 */
export type RenderedSample = {
  function_name: string;
  input: ModelInput;
  stored_input: StoredInput;
  output: Array<ContentBlockChatOutput> | null;
  stored_output: StoredOutput | null;
  dispreferred_outputs: Array<Array<ContentBlockChatOutput>>;
  episode_id: string | null;
  inference_id: string | null;
  output_schema: JsonValue | null;
  tags: { [key in string]?: string };
  /**
   * A subset of static tools configured for the function that the inference is allowed to use. Optional.
   * If not provided, all static tools are allowed.
   */
  allowed_tools?: Array<string>;
  /**
   * Tools that the user provided at inference time (not in function config), in addition to the function-configured
   * tools, that are also allowed.
   */
  additional_tools?: Array<FunctionTool>;
  /**
   * User-specified tool choice strategy. If provided during inference, it will override the function-configured tool choice.
   * Optional.
   */
  tool_choice?: ToolChoice;
  /**
   * Whether to use parallel tool calls in the inference. Optional.
   * If provided during inference, it will override the function-configured parallel tool calls.
   */
  parallel_tool_calls?: boolean;
  /**
   * Provider-specific tool configurations
   */
  provider_tools: Array<ProviderTool>;
};
