// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlock } from "./ContentBlock";
import type { Role } from "./Role";

/**
 * A RequestMessage is a message sent to a model
 */
export type RequestMessage = { role: Role, content: Array<ContentBlock>, };
