// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
// Backwards-compatibility alias for ResolvedTomlPathData.

import type { ResolvedTomlPathData } from "./ResolvedTomlPathData";

/**
 * Deprecated: use ResolvedTomlPathData instead.
 */
