// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectStorageFile } from "./ObjectStorageFile";
import type { Text } from "./Text";
import type { Thought } from "./Thought";
import type { ToolCall } from "./ToolCall";
import type { ToolResult } from "./ToolResult";
import type { Unknown } from "./Unknown";

/**
 * Like `ContentBlock`, but stores an in-memory `ObjectStorageFile` instead of a `LazyFile`
 * As a result, it can implement both `Serialize` and `Deserialize`
 */
export type ResolvedContentBlock =
  | ({ type: "text" } & Text)
  | ({ type: "tool_call" } & ToolCall)
  | ({ type: "tool_result" } & ToolResult)
  | ({ type: "file" } & ObjectStorageFile)
  | ({ type: "thought" } & Thought)
  | ({ type: "unknown" } & Unknown);
