// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wrapper type to enforce proper handling of toml-relative paths for files.
 * When we add support for config globbing, we'll require deserializing
 * all paths (e.g. `system_schema`) as `ResolvedTomlPath`s, which will
 * track the original `.toml` file in order to perform correct relative path resolution.
 */
export type ResolvedTomlPathData = {
  __tensorzero_remapped_path: string;
  /**
   * This should contain the data that was stored at the path above
   */
  __data: string;
};
