// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvaluationConfig } from "./EvaluationConfig";
import type { EvaluationFunctionConfig } from "./EvaluationFunctionConfig";
import type { UninitializedVariantInfo } from "./UninitializedVariantInfo";

/**
 * Request body for running an evaluation.
 */
export type RunEvaluationRequest = {
  /**
   * URL of the gateway to use for inference requests
   */
  gateway_url: string;
  /**
   * URL of the ClickHouse database
   */
  clickhouse_url: string;
  /**
   * The evaluation configuration (serialized)
   */
  evaluation_config: EvaluationConfig;
  /**
   * The function configuration for output schema validation
   */
  function_config: EvaluationFunctionConfig;
  /**
   * Name of the evaluation
   */
  evaluation_name: string;
  /**
   * Name of the dataset to evaluate (optional, either this or datapoint_ids must be provided)
   */
  dataset_name?: string;
  /**
   * Specific datapoint IDs to evaluate (optional)
   */
  datapoint_ids?: Array<string>;
  /**
   * Variant to use: either a variant name or a dynamic variant configuration
   */
  variant_name?: string;
  /**
   * Dynamic variant configuration (alternative to variant_name)
   */
  internal_dynamic_variant_config?: UninitializedVariantInfo;
  /**
   * Number of concurrent requests
   */
  concurrency: number;
  /**
   * Cache mode for inference requests
   */
  inference_cache: string;
  /**
   * Maximum number of datapoints to evaluate
   */
  max_datapoints?: number;
  /**
   * Per-evaluator precision targets for adaptive stopping
   */
  precision_targets?: { [key in string]?: number };
};
