// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StaticJSONSchema } from "./StaticJSONSchema";

/**
 * Holds all of the schemas used by a chat completion function.
 * These are used by variants to construct a `TemplateWithSchema`
 */
export type SchemaData = {
  [key in string]?: { schema: StaticJSONSchema; legacy_definition: boolean };
};
