// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Field to sort sessions by.
 */
export type SessionSortField = "created_at" | "last_event_at";
