// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Base64FileMetadata } from "./Base64FileMetadata";
import type { StoragePath } from "./StoragePath";

export type StoredFile = { file: Base64FileMetadata, storage_path: StoragePath, };
