// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for the object storage backend
 * Currently, we only support S3-compatible object storage and local filesystem storage
 * We test against Amazon S3, GCS, Cloudflare R2, and Minio
 */
export type StorageKind =
  | {
      type: "s3_compatible";
      bucket_name?: string;
      region?: string;
      endpoint?: string;
      allow_http?: boolean;
    }
  | { type: "filesystem"; path: string }
  | { type: "disabled" };
