// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectStorageFile } from "./ObjectStorageFile";

/**
 * A newtype wrapper around `ObjectStorageFile` that handles legacy deserialization formats.
 * This ensures `StoredFile` stays in sync with `ObjectStorageFile` and prevents type drift.
 *
 * The custom deserializer handles:
 * - Legacy nested format: `{ file: { source_url, mime_type }, storage_path }`
 * - Legacy alias: `{ image: { source_url, mime_type }, storage_path }`
 * - New flattened format: `{ source_url, mime_type, storage_path }` (delegates to ObjectStorageFile)
 * - Deprecated `url` field (via ObjectStorageFile): `{ url: ..., mime_type, storage_path }`
 */
export type StoredFile = ObjectStorageFile;
