// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlockChatOutput } from "./ContentBlockChatOutput";
import type { DynamicToolParams } from "./DynamicToolParams";
import type { StoredInput } from "./StoredInput";

/**
 * Wire variant of StoredChatInference for API responses with Python/TypeScript bindings
 */
export type StoredChatInference = {
  function_name: string;
  variant_name: string;
  input: StoredInput;
  output: Array<ContentBlockChatOutput>;
  dispreferred_outputs: Array<Array<ContentBlockChatOutput>>;
  timestamp: string;
  episode_id: string;
  inference_id: string;
  tool_params: DynamicToolParams;
  tags: { [key in string]?: string };
};
