// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoredFile } from "./StoredFile";
import type { Text } from "./Text";
import type { Thought } from "./Thought";
import type { ToolCall } from "./ToolCall";
import type { ToolResult } from "./ToolResult";
import type { Unknown } from "./Unknown";

/**
 * The version of `ContentBlock` that is stored in ClickHouse.
 * This is almost identical to `ContentBlock`, but without `File` data.
 */
export type StoredContentBlock =
  | ({ type: "text" } & Text)
  | ({ type: "tool_call" } & ToolCall)
  | ({ type: "tool_result" } & ToolResult)
  | ({ type: "file" } & StoredFile)
  | ({ type: "thought" } & Thought)
  | ({ type: "unknown" } & Unknown);
