// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoredFile } from "./StoredFile";
import type { Thought } from "./Thought";
import type { ToolCall } from "./ToolCall";
import type { ToolResult } from "./ToolResult";
import type { JsonValue } from "./serde_json/JsonValue";

export type StoredInputMessageContent =
  | { type: "text"; value: JsonValue }
  | {
      type: "template";
      name: string;
      arguments: { [key in string]?: JsonValue };
    }
  | ({ type: "tool_call" } & ToolCall)
  | ({ type: "tool_result" } & ToolResult)
  | { type: "raw_text"; value: string }
  | ({ type: "thought" } & Thought)
  | ({ type: "file" } & StoredFile)
  | { type: "unknown"; data: JsonValue; model_provider_name: string | null };
