// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoredChatInferenceWire } from "./StoredChatInferenceWire";
import type { StoredJsonInference } from "./StoredJsonInference";

/**
 * Wire variant of StoredInference for API responses with Python/TypeScript bindings
 */
export type StoredInferenceWire =
  | ({ type: "chat" } & StoredChatInferenceWire)
  | ({ type: "json" } & StoredJsonInference);
