// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectStoragePointer } from "./ObjectStoragePointer";

/**
 * A newtype wrapper around `ObjectStoragePointer` that handles legacy deserialization formats.
 * See the deserializer implementation below for details on the legacy formats it supports.
 */
export type StoredFile = ObjectStoragePointer;
