// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query parameters for streaming events.
 */
export type StreamEventsParams = {
  /**
   * Resume streaming from this event ID (exclusive).
   */
  last_event_id?: string;
};
