// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StreamingTimeouts = {
  /**
   * The time allowed for the first token to be produced.
   */
  ttft_ms: bigint | null;
};
