// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutopilotStatus } from "./AutopilotStatus";
import type { Event } from "./Event";

export type StreamUpdate = { event: Event; status: AutopilotStatus };
