// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Arguments } from "./Arguments";

export type Template = { name: string; arguments: Arguments };
