// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedTomlPathDirectory } from "./ResolvedTomlPathDirectory";

export type TemplateFilesystemAccess = {
  /**
   * If `true`, allow minijinja to read from the filesystem (within the tree of the config file) for `{% include %}`
   * Defaults to `false`
   */
  enabled: boolean;
  base_path: ResolvedTomlPathDirectory | null;
};
