// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TensorZeroRelayTargetType =
  | { type: "function"; function_name: string; variant_name: string | null }
  | { type: "model"; model_name: string };
