// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Arguments } from "./Arguments";

/**
 * Helper enum for deserializing legacy text content formats.
 */
export type TextKind = { text: string } | { arguments: Arguments };
