// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Minimal job handle for Together SFT.
 * All configuration needed for polling comes from provider_types at poll time.
 */
export type TogetherSFTJobHandle = {
  job_id: string;
  /**
   * A url to a human-readable page for the job.
   */
  job_url: string;
};
