// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialLocationWithFallback } from "./CredentialLocationWithFallback";

export type TogetherDefaults = {
  api_key_location: CredentialLocationWithFallback;
};
