// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wrapper type to enforce proper handling of toml-relative paths.
 * When we add support for config globbing, we'll require deserializing
 * all paths (e.g. `system_schema`) as `TomlRelativePath`s, which will
 * track the original `.toml` file in order to perform correct relative path resolution.
 */
export type TomlRelativePath = { path: string };
