// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionToolConfig } from "./FunctionToolConfig";
import type { OpenAICustomTool } from "./OpenAICustomTool";

export type ToolConfig =
  | { Function: FunctionToolConfig }
  | { OpenAICustom: OpenAICustomTool };
