// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientSideFunctionToolConfig } from "./ClientSideFunctionToolConfig";
import type { OpenAICustomTool } from "./OpenAICustomTool";

export type ToolConfig =
  | { ClientSideFunction: ClientSideFunctionToolConfig }
  | { OpenAICustom: OpenAICustomTool };
