// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tool } from "./Tool";
import type { ToolChoice } from "./ToolChoice";

/**
 * ToolCallConfigDatabaseInsert is a lightweight version of ToolCallConfig that can be serialized and cloned.
 * It is used to insert the ToolCallConfig into the database.
 */
export type ToolCallConfigDatabaseInsert = { tools_available: Array<Tool>, tool_choice: ToolChoice, parallel_tool_calls: boolean | null, };
