// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Evaluator that checks whether an inference's tool calls match the expected behavior.
 */
export type ToolUseConfig =
  | { behavior: "none"; cutoff?: number }
  | { behavior: "none_of"; tools: Array<string>; cutoff?: number }
  | { behavior: "any"; cutoff?: number }
  | { behavior: "any_of"; tools: Array<string>; cutoff?: number }
  | { behavior: "all_of"; tools: Array<string>; cutoff?: number };
