// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCallDecisionSource } from "./ToolCallDecisionSource";
import type { ToolResult } from "./ToolResult";

export type ToolOutcome =
  | ({ type: "success" } & ToolResult)
  | { type: "failure"; message: string }
  | { type: "missing" }
  | { type: "rejected"; source: ToolCallDecisionSource; reason: string }
  | { type: "other" };
