// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolUseBehavior } from "./ToolUseBehavior";

/**
 * Evaluator that checks whether an inference's tool calls match the expected behavior.
 *
 * `tools` is required for `none_of`, `any_of`, and `all_of` behaviors,
 * and must not be specified for `none` and `any`.
 */
export type ToolUseConfig = {
  /**
   * The matching rule to apply to the inference's tool calls.
   */
  behavior: ToolUseBehavior;
  /**
   * Tool names to match against. Required for `none_of`, `any_of`, and `all_of` behaviors.
   */
  tools?: Array<string>;
  cutoff?: number;
};
