// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A Tool object describes how a tool can be dynamically configured by the user.
 */
export type Tool = { description: string, parameters: JsonValue, name: string, strict: boolean, };
