// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllowedTools } from "./AllowedTools";
import type { ProviderTool } from "./ProviderTool";
import type { ToolChoice } from "./ToolChoice";
import type { ToolConfig } from "./ToolConfig";

/**
 * Contains all information required to tell an LLM what tools it can call
 * and what sorts of tool calls (parallel, none, etc) it is allowed to respond with.
 * Most inference providers can convert this into their desired tool format.
 */
export type ToolCallConfig = {
  tools_available: Array<ToolConfig>;
  provider_tools: Array<ProviderTool>;
  tool_choice: ToolChoice;
  parallel_tool_calls: boolean | null;
  allowed_tools: AllowedTools;
};
