// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A ToolCallOutput is a request by a model to call a Tool
 * in the form that we return to the client / ClickHouse
 */
export type ToolCallOutput = {
  arguments?: JsonValue;
  id: string;
  name?: string;
  raw_arguments: string;
  raw_name: string;
};
