// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VariantSummary } from "./VariantSummary";

/**
 * Visualization data for a top-k evaluation.
 */
export type TopKEvaluationVisualization = {
  /**
   * Map of variant names to their summary statistics.
   */
  variant_summaries: { [key in string]: VariantSummary };
};
