// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Nursery } from "./Nursery";

/**
 * Public representation of Track-and-Stop state for external callers (tests, UI, monitoring).
 * This type exposes sampling probabilities but hides internal implementation details like
 * the `Nursery` struct and atomic counters.
 */
export type TrackAndStopState =
  | { type: "stopped"; winner_variant_name: string }
  | ({ type: "nursery_only" } & Nursery)
  | {
      type: "bandits_only";
      sampling_probabilities: { [key in string]?: number };
    }
  | {
      type: "nursery_and_bandits";
      nursery: Nursery;
      sampling_probabilities: { [key in string]?: number };
    }
  | {
      type: "nursery_and_stopped";
      nursery: Nursery;
      stopped_variant_name: string;
    };
