// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvaluationConfig } from "./EvaluationConfig";
import type { FunctionConfig } from "./FunctionConfig";
import type { MetricConfig } from "./MetricConfig";
import type { StaticToolConfig } from "./StaticToolConfig";

/**
 * Response type for GET /internal/ui-config
 *
 * Contains only UI-safe fields from the gateway config, excluding sensitive
 * information like provider credentials, API keys, and internal settings.
 */
export type UiConfig = {
  functions: { [key in string]?: FunctionConfig };
  metrics: { [key in string]?: MetricConfig };
  tools: { [key in string]?: StaticToolConfig };
  evaluations: { [key in string]?: EvaluationConfig };
  model_names: Array<string>;
};
