// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InferenceExtraHeader } from "./InferenceExtraHeader";

/**
 * The 'InferenceExtraHeaders' options provided directly in an inference request
 * These have not yet been filtered by variant name
 */
export type UnfilteredInferenceExtraHeaders = {
  extra_headers: Array<InferenceExtraHeader>;
};
