// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtraBody } from "./ExtraBody";

/**
 * The 'InferenceExtraBody' options provided directly in an inference request.
 * These have not yet been filtered by variant name
 */
export type UnfilteredInferenceExtraBody = { extra_body: Array<ExtraBody> };
