// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeoutsConfig } from "./TimeoutsConfig";
import type { UninitializedBestOfNSamplingConfig } from "./UninitializedBestOfNSamplingConfig";
import type { UninitializedChainOfThoughtConfig } from "./UninitializedChainOfThoughtConfig";
import type { UninitializedChatCompletionConfig } from "./UninitializedChatCompletionConfig";
import type { UninitializedDiclConfig } from "./UninitializedDiclConfig";
import type { UninitializedMixtureOfNConfig } from "./UninitializedMixtureOfNConfig";

export type UninitializedVariantInfo = { timeouts: TimeoutsConfig | null } & (
  | ({ type: "chat_completion" } & UninitializedChatCompletionConfig)
  | ({
      type: "experimental_best_of_n_sampling";
    } & UninitializedBestOfNSamplingConfig)
  | ({
      type: "experimental_dynamic_in_context_learning";
    } & UninitializedDiclConfig)
  | ({ type: "experimental_mixture_of_n" } & UninitializedMixtureOfNConfig)
  | ({
      type: "experimental_chain_of_thought";
    } & UninitializedChainOfThoughtConfig)
);
