// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenAIGrader } from "./OpenAIGrader";
import type { OpenAIRFTResponseFormat } from "./OpenAIRFTResponseFormat";

export type UninitializedOpenAIRFTConfig = {
  model: string;
  grader: OpenAIGrader;
  response_format?: OpenAIRFTResponseFormat;
  batch_size?: number;
  compute_multiplier?: number;
  eval_interval?: number;
  eval_samples?: number;
  learning_rate_multiplier?: number;
  n_epochs?: number;
  reasoning_effort?: string;
  api_base?: string;
  seed?: bigint;
  suffix?: string;
};
