// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtraBodyConfig } from "./ExtraBodyConfig";
import type { ExtraHeadersConfig } from "./ExtraHeadersConfig";
import type { JsonMode } from "./JsonMode";
import type { ResolvedTomlPath } from "./ResolvedTomlPath";
import type { RetryConfig } from "./RetryConfig";

export type UninitializedDiclConfig = {
  weight: number | null;
  embedding_model: string;
  k: number;
  model: string;
  system_instructions: ResolvedTomlPath | null;
  temperature: number | null;
  top_p: number | null;
  stop_sequences: Array<string> | null;
  presence_penalty: number | null;
  frequency_penalty: number | null;
  max_tokens: number | null;
  seed: number | null;
  json_mode: JsonMode | null;
  extra_body: ExtraBodyConfig | null;
  retries: RetryConfig;
  extra_headers: ExtraHeadersConfig | null;
};
