// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UninitializedFunctionConfigChat } from "./UninitializedFunctionConfigChat";
import type { UninitializedFunctionConfigJson } from "./UninitializedFunctionConfigJson";

export type UninitializedFunctionConfig =
  | ({ type: "chat" } & UninitializedFunctionConfigChat)
  | ({ type: "json" } & UninitializedFunctionConfigJson);
