// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TomlRelativePath } from "./TomlRelativePath";

export type UninitializedInputWrappers = {
  user: TomlRelativePath | null;
  assistant: TomlRelativePath | null;
  system: TomlRelativePath | null;
};
