// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UninitializedTogetherSFTConfig = { model: string, credentials: string | null, api_base: string | null, };
