// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedTomlPathData } from "./ResolvedTomlPathData";
import type { ToolChoice } from "./ToolChoice";
import type { UninitializedExperimentationConfigWithNamespaces } from "./UninitializedExperimentationConfigWithNamespaces";
import type { UninitializedSchemas } from "./UninitializedSchemas";
import type { UninitializedVariantInfo } from "./UninitializedVariantInfo";

export type UninitializedFunctionConfigChat = {
  variants: { [key in string]: UninitializedVariantInfo };
  system_schema?: ResolvedTomlPathData;
  user_schema?: ResolvedTomlPathData;
  assistant_schema?: ResolvedTomlPathData;
  schemas: UninitializedSchemas;
  tools: Array<string>;
  tool_choice: ToolChoice;
  parallel_tool_calls?: boolean;
  description?: string;
  experimentation?: UninitializedExperimentationConfigWithNamespaces;
};
