// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UninitializedGCPVertexGeminiSFTConfig = { model: string, bucket_name: string, project_id: string, region: string, learning_rate_multiplier: number | null, adapter_size: number | null, n_epochs: number | null, export_last_checkpoint_only: boolean | null, credentials: string | null, api_base: string | null, seed: bigint | null, service_account: string | null, kms_key_name: string | null, tuned_model_display_name: string | null, bucket_path_prefix: string | null, };
