// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialLocationWithFallback } from "./CredentialLocationWithFallback";
import type { TogetherBatchSize } from "./TogetherBatchSize";
import type { TogetherLRScheduler } from "./TogetherLRScheduler";
import type { TogetherTrainingMethod } from "./TogetherTrainingMethod";
import type { TogetherTrainingType } from "./TogetherTrainingType";

export type UninitializedTogetherSFTConfig = {
  model: string;
  credentials?: CredentialLocationWithFallback;
  api_base?: string;
  n_epochs: number;
  n_checkpoints: number;
  n_evals?: number;
  batch_size: TogetherBatchSize;
  learning_rate: number;
  warmup_ratio: number;
  max_grad_norm: number;
  weight_decay: number;
  suffix?: string;
  lr_scheduler: TogetherLRScheduler;
  wandb_api_key?: string;
  wandb_base_url?: string;
  wandb_project_name?: string;
  wandb_name?: string;
  training_method: TogetherTrainingMethod;
  training_type: TogetherTrainingType;
  from_checkpoint?: string;
  from_hf_model?: string;
  hf_model_revision?: string;
  hf_api_token?: string;
  hf_output_repo_name?: string;
};
