// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UninitializedSchema } from "./UninitializedSchema";

export type UninitializedSchemas = {
  inner: { [key in string]: UninitializedSchema };
};
