// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StaticWeightsConfig } from "./StaticWeightsConfig";
import type { UniformConfig } from "./UniformConfig";
import type { UninitializedTrackAndStopConfig } from "./UninitializedTrackAndStopConfig";

export type UninitializedExperimentationConfig =
  | ({ type: "static_weights" } & StaticWeightsConfig)
  | ({ type: "uniform" } & UniformConfig)
  | ({ type: "track_and_stop" } & UninitializedTrackAndStopConfig);
