// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UninitializedBestOfNEvaluatorConfig } from "./UninitializedBestOfNEvaluatorConfig";

export type UninitializedBestOfNSamplingConfig = {
  weight: number | null;
  timeout_s: number;
  candidates: Array<string>;
  evaluator: UninitializedBestOfNEvaluatorConfig;
};
