// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialLocationWithFallback } from "./CredentialLocationWithFallback";

export type UninitializedFireworksSFTConfig = {
  model: string;
  early_stop: boolean | null;
  epochs: number | null;
  learning_rate: number | null;
  max_context_length: number | null;
  lora_rank: number | null;
  batch_size: number | null;
  display_name: string | null;
  output_model: string | null;
  warm_start_from: string | null;
  is_turbo: boolean | null;
  eval_auto_carveout: boolean | null;
  nodes: number | null;
  mtp_enabled: boolean | null;
  mtp_num_draft_tokens: number | null;
  mtp_freeze_base_model: boolean | null;
  credentials: CredentialLocationWithFallback | null;
  account_id: string;
  api_base: string | null;
};
