// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeoutsConfig } from "./TimeoutsConfig";
import type { UninitializedModelProvider } from "./UninitializedModelProvider";

export type UninitializedModelConfig = {
  routing: Array<string>;
  providers: { [key in string]?: UninitializedModelProvider };
  timeouts: TimeoutsConfig;
};
