// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeoutsConfig } from "./TimeoutsConfig";
import type { UninitializedLLMJudgeBestOfNVariantConfig } from "./UninitializedLLMJudgeBestOfNVariantConfig";
import type { UninitializedLLMJudgeChainOfThoughtVariantConfig } from "./UninitializedLLMJudgeChainOfThoughtVariantConfig";
import type { UninitializedLLMJudgeChatCompletionVariantConfig } from "./UninitializedLLMJudgeChatCompletionVariantConfig";
import type { UninitializedLLMJudgeDiclVariantConfig } from "./UninitializedLLMJudgeDiclVariantConfig";
import type { UninitializedLLMJudgeMixtureOfNVariantConfig } from "./UninitializedLLMJudgeMixtureOfNVariantConfig";

export type UninitializedLLMJudgeVariantInfo = {
  timeouts: TimeoutsConfig | null;
} & (
  | ({
      type: "chat_completion";
    } & UninitializedLLMJudgeChatCompletionVariantConfig)
  | ({
      type: "experimental_best_of_n_sampling";
    } & UninitializedLLMJudgeBestOfNVariantConfig)
  | ({
      type: "experimental_mixture_of_n";
    } & UninitializedLLMJudgeMixtureOfNVariantConfig)
  | ({
      type: "experimental_dynamic_in_context_learning";
    } & UninitializedLLMJudgeDiclVariantConfig)
  | ({
      type: "experimental_chain_of_thought";
    } & UninitializedLLMJudgeChainOfThoughtVariantConfig)
);
