// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateDatapointsMetadataRequest } from "./UpdateDatapointsMetadataRequest";

export type UpdateDatapointsMetadataParams = {
  dataset_name: string;
  request: UpdateDatapointsMetadataRequest;
};
