// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateDatapointRequest } from "./UpdateDatapointRequest";

/**
 * Request to update one or more datapoints in a dataset.
 */
export type UpdateDatapointsRequest = {
  /**
   * The datapoints to update.
   */
  datapoints: Array<UpdateDatapointRequest>;
};
