// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Detail } from "./Detail";

/**
 * A file that can be located at a URL
 */
export type UrlFile = {
  url: string;
  mime_type: string | null;
  detail?: Detail;
  filename?: string;
};
