// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputTokensDetails } from "./InputTokensDetails";
import type { OutputTokensDetails } from "./OutputTokensDetails";

export type Usage = {
  input_tokens?: number;
  output_tokens?: number;
  input_tokens_details?: InputTokensDetails;
  output_tokens_details?: OutputTokensDetails;
};
