// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary statistics for a variant's performance.
 */
export type VariantSummary = {
  /**
   * Estimated mean performance.
   */
  mean_est: number;
  /**
   * Lower confidence bound.
   */
  cs_lower: number;
  /**
   * Upper confidence bound.
   */
  cs_upper: number;
  /**
   * Number of observations.
   */
  count: bigint;
};
