// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TopKEvaluationVisualization } from "./TopKEvaluationVisualization";

/**
 * Types of visualizations that can be displayed.
 */
export type VisualizationType = {
  type: "top_k_evaluation";
} & TopKEvaluationVisualization;
