// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VLLMDefaults } from "./VLLMDefaults";

export type VLLMProviderTypeConfig = { defaults: VLLMDefaults };
