// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a single workflow evaluation run episode with feedback.
 */
export type WorkflowEvaluationRunEpisodeWithFeedback = {
  episode_id: string;
  timestamp: string;
  run_id: string;
  tags: { [key in string]?: string };
  task_name?: string;
  /**
   * The feedback metric names, sorted alphabetically.
   */
  feedback_metric_names: Array<string>;
  /**
   * The feedback values, corresponding to the metric names.
   */
  feedback_values: Array<string>;
};
