// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UninitializedOpenAISFTConfig = { model: string, batch_size: number | null, learning_rate_multiplier: number | null, n_epochs: number | null, credentials: string | null, api_base: string | null, seed: bigint | null, suffix: string | null, };
