name: Dummy

on:
  pull_request:
    branches: ["main"]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: false

jobs:
  # See 'ci/README.md' at the repository root for more details.
  merge-checks-buildkite:
    name: merge-checks-buildkite
    runs-on: ubuntu-latest
    if: github.repository == 'tensorzero/tensorzero'
    steps:
      - run: echo "This is a dummy job to satisfy branch protection checks"
